### ISSUE TITLE
initial database creation

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#10]
When user creates a new database then initial Compendium data are loaded into it. This shouldn't happen. When user creates db then he/she does it via dialog. There should be 2 checkboxes:

[] populate the database with Compendium Project data
[] populate the database with example data

un-checked by default so by default there are no extra data when db is created.

**Comment by SebastianBoell** [comment]
This is related to issue #32 

The Idea to make the initial data selectable is great! I would go with only one category called 'include example data'. Also I would suggest to have the box checked when the dialogue is opened. - The reason for my suggetion is to make sure that new users will get some form of introduction when they open a new project that briefly introduces the usage and also gives credit to earlier and current developers :).

Advanced users will have no problem in unchecking the box when they create a new project. From my personal experience creating projects is not a frequent event as most of the time users will work with projects they already created. In my opinion is the problem of a new user 'forgetting' to check the box more severe than of an advanced user forgetting to un-check?

**Comment by maiklos** [comment]
#### first terminology - _map_ vs _database_ vs _InformationBase_ (IB)

I use map and database interchangeably here but I would like to coin a new term since neither map nor database covers all the content which will be handled by CompendiumNG. My proposal is "Information Base"

definition: Information Base  is a set of documents, data, references, tags, history and caches that are handled by CompendiumNG application under Information Base ID.
IB besides of mentioned data contains also meta-data about user or IB itself (i.e. unique Id, name, ...)

# M1

in M1 we would start with "empty" space - when user create a new db then it will be "empty"
Populating of a map with anything should happen only as a result of user's exp...that user's "explicit request" would be "load template xyz" (initial creation dialog) where xyz is selected template from categorized list/tree of templates/examples available online and cached somewhere in compendium(rather user) directory.
licit request and that explicit action request could be triggered after db is already created
For M1 that explicit request could be implemented via import feature. 

btw. IMO credit should go to the About box (where it is expected)

# M?

for M? there should be something like online catalog available with pre-made IB's

### Compendium Catalog

a published index of pre-made IBs. Catalog itself would be created on and fetched from a site where examples/help/template IB's are provided and published (which doesn't exist as of now) 

### published IB types (tree list with classified IB's)
- templates (are meant to be used and extended)
- examples (are meant to be learned from)
- tutorial (to be studies)
- published (are meant to be cloned, extended, shared and eventually to be contributed to - bit like wiki)

### IB  creation

db creation dialog allows to select one of maps from Compendium Catalog and populate your database with data from that published map. This population of IB from published (or other IB) should be possible even
after IB is already created and contains some data (i.e. File->Add data->local|online->apply)

**Comment by SebastianBoell** [comment]
a)
Ok let's call this an information base. I guess from an user perspective an IB~Project? That is one project will have one IB and one IB is tied to one project?

b)
Absolut credits should be in the about box. I was thinking of some small sample data similar to what is currently included when a new project is created.

c)
Online catalogue: Absolutely **this is a great idea**. Having an online repository of use cases is how different templates ideally should be handeled. Possibly users should be able to create new 'templates' for projects and push them up there. I guess developing great and insightful templates is something we don't have to worry too much about if we create the right tools to create and share them. Then the compendium user community will be able to create templates for different use scenarios. IMO IBIS methodology for argument mapping should be regarded as only one type among many. From the discussion at the mailing list people use Compendium in many different creative ways and I am sure people are eager to develop and share their templates.

d)

### One important aspect of this is in my opinion that Compendium needs to provide the ability to be more flexible in creating:
- stencils - that is different types of nodes with different pictures (not handled well in current version which is mostly focussed around IBIS)
- links - different types of associations between nodes (currently the ability to adjust links is handled much better than the ability to adjust nodes)

e)
Also an IB (project) should be contained in one file which will allow to exchange projects between users and machines or creating backups easily by exchanging this file.

**Comment by maiklos** [comment]
ad a)
note: IB related things should go to #21 or to a ticket in the same milestone(M3). New storage will the primary focus of M3

IB project - I suspect ppl will tend to call it compendium project but this names are primarily for developing side - to unify identifiers in the code.

ad b)
also related to #23 

ad c)
I will create a new project/module for this called CompendiumExchange and tried to summarize it in README file.
We will need online hosting probably soon since some basic features of ComendiumExchange will be needed early.

ad d)
Stencils - I would go with the same approach: let the community to extend them just provide them to possibility (online)

ad e)
agree: this is requirement that should go to #21

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/when-a-new-project-is-created-users-should-have-the-option-for-it-to-contain-no-example-data/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
