### ISSUE TITLE
Collect and consolidate: feature suggestions and suggestions from Bugzilla and others

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#106]
Collect all feature suggestions from bugzilla and other sources. Review and structure them into common groups that can be used for planning future development. For instance, a group of feature suggestions may be closely related or interdependent that enables or requires to implement them together. There are several resources to be drawn from for this issue:
- 30 [DONE] [Feature suggestions in bugzilla made regarding Compendium 2.0](http://compendium.open.ac.uk/bugzilla/buglist.cgi?query_format=advanced&bug_severity=Feature%20Request&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=VERIFIED&version=2.0%20Alpha%209&version=2.0%20Beta%201&product=Compendium)
- 150 [DONE] [Feature suggestiond in bugzilla made independently of a particular version of Compendium](http://compendium.open.ac.uk/bugzilla/buglist.cgi?query_format=advanced&bug_severity=Feature%20Request&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=VERIFIED&version=other&product=Compendium)
- 196 [DONE] [Feature suggestions in bugzilla made regarding to Compendium version 1.4 to 1.5](http://compendium.open.ac.uk/bugzilla/buglist.cgi?query_format=advanced&bug_severity=Feature%20Request&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=VERIFIED&version=1.4&version=1.4.1&version=1.5&version=1.5.1&version=1.5.2&version=1.5.3%20Alpha%201&version=1.5.3%20Alpha%202&version=1.5.3%20Alpha%203&version=1.5.3%20Alpha%204&version=1.5.3%20Alpha%205&product=Compendium) that should be reviewed if they may apply to CompendiumNG
- 8 [DONE] Feature suggestions that where hidden in support queries for Compendium 2.0
- ~30 [DONE] [Suggestions that were made in a virtual meeting regarding compendium features in December 2012 ](http://www.cognexus.org/Compendium_Futures/User_Functionality_Webmap/C_User_Functionality_Home.html)
- 17 [Feature suggestions already in the issue system here](https://github.com/CompendiumNG/CompendiumNG/issues?labels=Type%3A+Feature&page=1&state=open)

I will slowly review all these and consolidate then. As discussed they will not be included as issues here. Given the number of issues we are dealing with and potential interconnections, duplicates, etc. I will do a first review using Compendium :))  So I added a compendium database in the docs folder of M1 _feature_suggestions_compendium_map.sql_ that will be continuously updated while I work my way through these suggestions over the next month. I will post some update stats here.

**Comment by mike223** [comment]
This old feature request about opening parent maps is marked FIXED RESOLVED in Bugzilla. But on the other hand it is marked as "Undecided Feature Request":
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=975

Would you please have a look if it is in fact FIXED already?
If not please put this "basic usability" feature request in your collection. I think it is quite important if Compendium is to be used for real work. 

Mike and his 15k nodes

**Comment by SebastianBoell** [comment]
As all feature suggestions are now imported into the feature suggestion map, and have been through an initial review a number of suggestions can be already marked as solved (#149), imported to here as bugs (#150), reported back to bugzilla as lacking enough detail to be addressed (#152). However, most of the feature suggestions that are valid, sensible and with enough detail need to be further reviewed (#151). All these tickets are threrefore continuation of this issue in different directions.

This current issue can therefore be closed.

**Comment by mike223** [comment]
Would you please leave a note on how one can open feature_suggestions_compendium_map.sql ?
It seems to be in a format that Compendium 2.0 Beta 1 cannot import directly.

**Comment by SebastianBoell** [comment]
Possibly the file on the server is corrupt. I tried importing the latest verion into 2.0b1 here without any issues. Will push an update to Github shortly hopefully this will resolve the issue. 

In any way you should go ahead and put you suggestions onto our [FSP](http://compendiumng.org/suggestions/) so people can start commenting and voting on your ideas.

**Comment by mike223** [comment]
Got it. Just didn't remember that the somewhat hidden Database Restore is working on .sql files.
