### ISSUE TITLE
Review user feedback systems for collecting feature requests

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#108]
Collecting feature requests through the issue system does not seem like a good idea:
1.  Our issue system may be clogged up by numberous suggestions over time ([see here for an article on this](http://37signals.com/svn/archives2/getting_real_forget_feature_requests.php); also issue #106 identifying already 400+ feature suggestions from users)
2.  The issue system does not allow a good means for users to comment and vote for different feature requests.

Instead the development system here should only include open items for features that the development team has agreed to work on as part of a current release (or in the forseeable future). Ideally a feature included here on GitHub should already including a clear pathway regarding the work necessary to include these features.

A good solution to this is using a user feedback system with voting function and commenting option for collecting user feedback regarding feature suggestions. And it needs to be free. Different alternatives exist and will be reviewed:
## wpmudev Q&A light wordpress plugin [CHOSEN]

[here](http://premium.wpmudev.org/project/qa-wordpress-questions-and-answers-plugin-lite). I have installed it on our wordpress site and it looks well. You need to be logged in to have a look [here](http://www.compendiumng.com/questions). Some issues would need to be resolved to make it fully workable but I made good progress on them already.
#### pro:
- open source code itself
- direct installation into wordpress, good integration into our homepage
- quite adjustable, if answers are dissabled it becomes a neat (not overwhelming) feature suggestion system with ability to up and downvote suggestions.
#### con:
- per default users need to be logged in to see suggestions
- The buttons on the main page are buggy, as they are only clickable in the lower quarter (very confusing)
- Users cannot vote on their own suggestions!
- (Login through our page is slightly more cumbersome than than one on uservoice)
## uservoice.com [maybe - account closed]

Is a commercially operated system that offers a free account with limited functionality. Nevertheless the offered functionality may be sufficient for our purpose. I created an [account](https://compendiumng.uservoice.com/admin) and set up a test: [Feature Suggestions and development ideas for CompendiumNG](https://compendiumng.uservoice.com)
#### pro:
- it looks quite neat (really simple interface with no additional fuzz)
- offers voting with limited number of votes per user
- allows sign in using facebook, google, or email (The sign on handling is really neat no email confirmation or typing in of capcha images required)
- allows to upload issues in bulk using csv, this may be especially handy for populating the service with the outcomes of issue #106
- enables integration into wordpress
- supports using [API](http://developer.uservoice.com/docs/api/reference/)
- content can be exported using API or CSV files should we decide to move on (however, we would need to sign up for one month for a 'basic' account; nevertheless I think this is not too much of a hurdle)
#### con:
- changing the layout is limited
- free account may be restricted in the future
- imited to one moderator
## Userecho.com [maybe - account closed]

I have created an [account on Userecho.com](http://compendiumng.userecho.com) for evaluation purposes. Currently waiting for them to get back about an non for profit account.
#### pro:
- Reported to provide free accounts for Open Source Projects.
- Some flexibility in setting up the appearance
- Can handle user Questions as well as Feature suggestions
- Offers some form of spam filter as part of the free version
- enables integration into wordpress
#### con:
- Appears a bit more 
- Users can not give multiple votes (say 1-3) for issues to indicate their preferences
- UI not as intuitive as others
- free account may be restricted in the future
- Limited to one moderator
## shapado.com [maybe]

[here](https://shapado.com/plans)
#### pro:
- shapado is open source and can be installed on our server for free
- the [user login from wordpress can be used for shapado as well](http://shapado.com/questions/want-to-integrate-wordpress-users-with-s), henc requiring only one login registration
#### con:
- The interface looks a bit complext with labels over the place and no clear indication of votes
- there is some means to integrate it into the look and feel of a wordpress page, however this does not seem to be a straight forward process [requering to have two templates in parallel](http://shapado.com/questions/can-shapado-also-host-my-wordpress-theme)
## Betaeasy.com [no]

[here](http://betaeasy.com)
#### con:
- Limited to 100 users (This really is an criteria for outright rejection!)
## Getsatisfaction.com [no - account closed]

I now created a test account [CompendiumNG on get Satisfaction](https://getsatisfaction.com/compendiumng)
#### pro:
- Enables Questions, Ideas, Praise and Bug reports
#### con:
- The functionality of the interface may be a tad too much for what we want
- free account may be restricted in the future
- Limited to one moderator
- Limited ability to adjust appearance
- I can't find a function for administration of inappropriate content or spam
## Idea.former.com [no - account closed]

I have created an [account on ideaformer](http://compendiumng.idea.informer.com) for evaluation purposes.
#### pro:
- Adjustment of look and feel is quite good (but also buggy)
#### con:
- There is no payed service, so the page may go bust more easily (see comment Michal)
- Troubles with setting up of verification through github
- Seems buggy
- The sign in procedure is annoying as users have to create an account first and cannot jump in right away.
## Google moderator [no - account closed]

This is an Q&A system. [A test account is available](http://www.google.com/moderator/#16/e=2046b4)
#### pro:
- It is free
#### con:
- seems to be less flexible with the layout and less intuitive, is designed for Q&A
## question2answer [no]

This is actually an Q&A system requiering a server to be set up on. [q2a website]([http://question2answer.org/)
#### pro:
- An open source project itself fits nicely into an open source ecosystem for CompendiumNG
- The layout seems to be very flexible 
#### con:
- Is designed for Q&A
- We will need a webserver where we can install Q2A
- Will need more time to set up and tweak the layout
# Even further options?

There is an overview page at Wikipedia: [Customer feedback management services](http://en.wikipedia.org/wiki/Customer_feedback_management_services)

**Comment by maiklos** [comment]
just thinking: 

voting is possible with jira but it contradicts what you have just written because it assumes that there is a ticket to vote on.

on the other side if we want to allow voting on bugs then we have to replicate such bug from issue tracker into the voting system.

btw. I have a virtual server at disposal which I am planning to use for compendium, so if there is a FOSS solution I can host it there.

**Comment by SebastianBoell** [comment]
Not sure if we should have voting on bugs. I guess we assess them and then put them in our system. Eventually bugs should be removed. In contrast not every feature suggestion should eventually be included. Just looking at the tons of suggestions we have already I just worry that we will end up with hundreds of (permanently) open tickets clogging up a meningful to do list. IMO our issue system should only include things that we are actually working on or at least seriously intend to work on. Nevertheless, something like the user feedback syste suggested here will allow users to pour their ideas.

Also: If you have a server what do you think of registering CompendiumNG.org? I guess we could (eventually) ralley for some financial support through the community.

**Comment by maiklos** [comment]
my criteria are following:
a) either hosted or FOSS for self-deployment
b) if hosted then must have paid pricing plans (more likely to survive)
c) if opensource user/developer community should be evaluated
d) metastack (i.e. stackoverflow.) approach seems a nice fit
e) some kind of integration with github would be nice
f) should support openid or oauth for simple user integration

**Comment by mike223** [comment]
I do not much like to have an additional interface for features. Already had to switch from Bugzilla to Github. You would need much to make me use two websites for a single piece of software. 
For me it was no problem that Bugzilla was containing bugs and feature requests together. Are there any of the people from the Open University complaing about?

One good reason for a second reporting system: Have a place for one-line "feature requests", user questions and community issues. But please leave the Github open for more detailed feature requests. 
Another problem is that there are issues somewhere between feature request and bug. And people will put issues into the "wrong" category. We would need an easy means to move issues between both. 
If you really want the features separated: How about another Github project with a name like "Feature Requests (CompendiumNG)"? It seems it should be possible to move or copy requests between CompendiumNG-Features and CompendiumNG:
http://stackoverflow.com/questions/9720718/how-do-i-move-an-issue-on-github-to-another-repo

One thing missing with this approach would be voting. But the count of people commenting on a feature request could be as good. 

Mike and his 15k nodes

**Comment by SebastianBoell** [comment]
I did not want to confuse you! 

Everything relevant for the development should be on this GitHub page **including features.**

The suggestion here was based on the assumption that [only a fraction of all feature suggestions are in the end something we can realise](http://37signals.com/svn/archives2/getting_real_forget_feature_requests.php). I guess for one user pulling left there is another pulling right, people want a software to do all sorts of things under the sun, and we simply cannot do them all. 

Also, the reason to have something like what is suggest here is to make user involvement easy and potentially less confusing for those who have never seen a website like GitHub before.

The idea is simply to avoid to initially collect all suggestions here.

**Comment by SebastianBoell** [comment]
After a lot of testing and deliberating, I selected the wpmudev Q&A worrdpress plugin for this job. It is open source itself, integrates completely into our wordpress site, and sufficiently adjustable to be molded into a feature suggestions and voting app. There are still some issues left to make it integrate flawlessly and I will now work through these (see issue #121).
