### ISSUE TITLE
node iterations seems slow

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#11]
when I do action on more nodes (i.e.) Ctrl-A [select-all-nodes] the action take quite some time. I suspect there is some issue with iteration/marking of all nodes. Investigate and try to improve  it.

**Comment by SebastianBoell** [comment]
I tested this on a smaller map and could not see any major issues. Possibly this would be related to 'bigger' maps (several hundreds of nodes). This is something to be tested with #234 when we have a benchmark map. I will re-classify this to 'Bug'.
We can re-open the issue when we see that there is a problem, for now I cannot reproduce and will close.
