### ISSUE TITLE
UI and keyboard shortcuts inconsistencies in list views 

### ISSUE THREAD

**Issue by mario-g** [CompendiumNG/CompendiumNG#112]
Keyboard shortcuts for list views are not consistent with kb shortcuts for map views.
In a list, the node being created (typing for example I, Q, M...) is not put in edit mode immediately after creation. The list view receives subsequent keyboard input not as text to put in the list element just created, but as a series of commands: typing "I All <Enter>" in a list view does not create an Answer node with text "All" but two answer nodes and two list nodes.

When the items are more than the number of rows which can be displayed in the window showing the list, it becomes rather difficult to add new items, because they show up at the end, without giving a visual sign of their creation. (EDIT: This issue has been already inserted https://github.com/CompendiumNG/CompendiumNG/issues/111)

Lists could be very useful for storing a lot of ideas in a small space but are affected by these shortcomings which make their usage impractical.

**Comment by SebastianBoell** [comment]
This issue is already reported as #111 I will close it. If there is anything we missed pleas add as a comment to #111.
