### ISSUE TITLE
Link two nodes without a direction

### ISSUE THREAD

**Issue by mario-g** [CompendiumNG/CompendiumNG#113]
May be related to https://github.com/CompendiumNG/CompendiumNG/issues/6

Often I want to create a relationship between nodes, but without a specified direction: I want node A to be related to node B, so that they are not taken apart by an auto arrange. Instead of selecting an arbitrary direction of the arrow, I'd like to set the direction only if I surely know it, increasing the quality of the data.

The non-directional link should not be graphical, but conceptual: the only constraint for auto arranging should be to put related nodes nearby, without the possibility to predict which node would go on each side. This would allow more nodes configurations when auto arranging, which could provide more insight on the topic. It could be also useful to enable creating visual clusters of related nodes, without the hurdle of thinking of a title when creating a view.

The link could be a grey dashed line, or better, a randomly coloured glow behind related nodes.

**Comment by SebastianBoell** [comment]
Hi Mario, improving auto arrangement is a good idea. Currently auto arrangement is very much focused on argument mapping. I will add your feature suggestion to the 400+ ideas we are currently reviewing as part of the migration to GitHub.

By the way, if you want to have nodes without a direction in your maps you can already do that by selecting 'no arrows' in the link formatting toolbar. You can also set your default link type to not have arrows under 'tools' 'manage link groups'. 

If you figure it out we also like to invite you to add a short question regarding how to format link types in our [FAQ](https://github.com/CompendiumNG/CompendiumNG/wiki/FAQ). This can help other users in the future having a similar problem.

**Comment by scribbly** [comment]
It would be nice to have this shortcut driven, somewhat like creation of new nodes == alt+<shortcut>, dragging out a link could be modified by a shortcut and / or a contextmenu shortcut (dragout link + contextmenu shortcut displays contextmenu of linktypes to select [e.g. similar to quick node linking]

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/improve-auto-arrangement-feature/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
