### ISSUE TITLE
Fix splash screen

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#115]
As indicated in #23 the splash screen should be updated to reflect the current development status and license, etc. of CompendiumNG

**Comment by maiklos** [comment]
we need to come up with content for it

**Comment by SebastianBoell** [comment]
I added screen shots and suggestions for content to the [wiki.](https://github.com/CompendiumNG/CompendiumNG/wiki/Splash-Screen)

**Comment by maiklos** [comment]
about background image is /application/src/main/resources/app-rsrc/images/splash.jpg
configurable in application/src/main/resources/config/main.properties
 -> key: system.splash.image

the other requested changes implemented

**Comment by SebastianBoell** [comment]
Thanks for that. I simply replaced the old splash image with a new one. Should not require to change the key. Let me know if the design is not working.

**Comment by SebastianBoell** [comment]
I reopen this for a quick change. Look at the [wiki](https://github.com/CompendiumNG/CompendiumNG/wiki/Splash-Screen). Above our tag line 'Connect you ideas' it should say 'CompendiumNG' where the original Splash said 'Compendium'. Hopefully easy to fix.
