### ISSUE TITLE
Remove UI elements that are no longer required or relevant

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#116]
As part of the development of CompendiumNG M1 some elements of the UI need to be removed as they are referring to capabilities that are no longer present. In particular the removal of fobs requires to remove all elements related to movie maps. (are there any other elements?)
- This issue is a result of the discussion related to #97 
- This issue is related to #117 which is to remove all corresponding references from the help system.
- There is an intend to bring back multimedia support after we found and implemented a replacement for fobs bhich was removed (see #118)

**Comment by maiklos** [comment]
moving this to 2.1.2

**Comment by alselvin** [comment]
We probably don't need the "memetic" item on the Tools menu.

![screen shot 2013-11-01 at 8 28 27 am](https://f.cloud.github.com/assets/5830715/1453378/280486fc-42f1-11e3-8583-5f88ba65ac84.png)

**Comment by maiklos** [comment]
are there still any parts that should be removed ?

**Comment by maiklos** [comment]
closing
