### ISSUE TITLE
Clean up help system in regards to movie maps

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#117]
As part of the M1 release we decided to remove multimedia support provided by fobs as fobs is no longer actively developed. We therefore need to remove all corresponding entries to movie maps in the help system.

**Comment by maiklos** [comment]
related to #157

**Comment by SebastianBoell** [comment]
I removed all references in the help system related to movie maps. At least I hope so :)

As I am new to working with Eclipse I was not sure on how to push a build from within it and fire up the help as it actually now looks like.
