### ISSUE TITLE
Prepare a first version of the CompendiumNG website

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#119]
Michal has kindly covered a first registration of compendiumNG.org. It would be great if we could set up a minimal website for a first release of Compendium M1 (preview 1). I don't know if it is overkill or too much work to set up a minimal wordpress installation for this? 

What the website needs to have:
- A short welcome message stating what CompendiumNG is (this can be taken from the readme.md file)
- A link to the Wiki here

So I guess this can be achieved with a single page. (I could do this.)

**Comment by maiklos** [comment]
content related to the website should go to CompendiumExchange project under CompendiumNG org.

the site is built with http://maven.apache.org/archetype/maven-archetype-bundles/maven-archetype-site-simple/

please read http://www.doclo.be/lieven/articles/personalsitewithmaven.html and plugin related documentation

to test it locally issue:
mvn site:run

and last line in the console will be something like this:
2013-01-10 16:27:35.672:INFO::jetty-6.1.25
2013-01-10 16:27:35.888:INFO::NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2013-01-10 16:27:36.358:INFO::Started SelectChannelConnector@0.0.0.0:53309

now point your web browser to http://localhost:53309

**Comment by SebastianBoell** [comment]
As I indicated I was playing around with wordpress to get a website up and running. Well I think it looks ok for a start. The final outcome is now up at www.compendiumng.com and you should have received details for an admin account as well. If you like we can move it over to www.CompendiumNG.org

I will upload all the artwork and other files to the CompendiumExchange project part. 

Also if you are happy with the website and the content I will reshape the wiki here to have a development focus rather than the general focus it had until now. In particular do I intend to remove duplacate content to make it easier to keep things up to date.

**Comment by maiklos** [comment]
please note that with commit 76a10 CompendiumExchange was merged into the main project as a submodule.
