### ISSUE TITLE
selecting and marking nodes on the map

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#12]
this is rather idea that should be thought over first:

when working with set of nodes the behavior should be improved. 
i.e. when you miss-click then all your selection is unselected.
or if you click on a link label area then the same happens.
This is very annoying when you have many nodes selected. 

behavior regarding node selection should be improved:
There should be "selecting" and "marking"
selecting - for simple ad-hoc operations
marking - selection made more "permanent"   (i.e. "mark selected nodes")  marked nodes remain persistent over  database close/open

consider marking x tagging (would it make sense implement "mark" as special case of a "tag" )
consider also "mark set", "named marked set", "convert marked nodes into selected nodes and vice versa" etc.

There should be following (usual) behavior in application for selecting nodes:

1 click on node - selects that particular node only
    1.1 when followed by escape key it restores previous selection
2 Ctrl-click on a node adds that particular node  to the selection
  2.2 Ctrl-click sub remove that particular from the selection
  2.3 click on some node -> rule 1 applies
3 Shift-click on a node same like - rule 2
   shift-click allows to add all nodes of within rectangulary surrounded area to the selection
   shift-click allows to remove all nodes  within rectangulary surrounded area to the selection when all nodes are are already selected

**Comment by SebastianBoell** [comment]
I think think this is a good idea to improve this. From my own experience of working with Compendium I think this is a important, but not a major issue. e.g. I regard fixing the zoom level as more important.

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/selecting-and-marking-nodes-on-the-map/> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
