### ISSUE TITLE
Curved links should be perpendicular to the edge of the bounding box

### ISSUE THREAD

**Issue by mario-g** [CompendiumNG/CompendiumNG#120]
Sometimes curved links are tangent to the bounding box of a node: for example an arrow has an horizontal direction when hits the bottom edge of the rectangle of the node, which is visually inappropriate.

**Comment by maiklos** [comment]
to demonstrate such behaviour:
setup:
![compendiumng-1](https://f.cloud.github.com/assets/251009/60156/fa791724-5bfc-11e2-9ce4-9e07b5afc4a1.png)
misbehaviour:
![compendiumng-2](https://f.cloud.github.com/assets/251009/60157/fe404c6a-5bfc-11e2-8f67-8ff8f957a192.png)

note there are 2 problems:
- arrow changed orientation when the arrow head is inside to surrounding box
- and problem as stated by mario-g

**Comment by SebastianBoell** [comment]
Curved links are really nice, but they can become a tricky thing to manage. I put this here as it is something else to consider with this problem.
![crossed links](https://f.cloud.github.com/assets/2730822/63424/965d1836-5ddb-11e2-88c3-5a98dfc67391.png)

As you can see in the picture at some point (angle) the curveage of links chages over. Visible here between 'question 4' and 'question 5'. It can become messy when links start to cross over, as demonstrated here with the 'a comment' node.

To fix this the curvage of the links should not be left to right and then right to left (imagine you drive a car down the link). Instead it should be gradual. To take the example it would be right to left at ever smaller angles untill there would be no curve and then the curvage should continue left to right at ever increasing angles. This is actually the case for the directions left, right, up and down as can be seen when looking at the nodes 'question', 'question 2' and 'question 3'. What is needed in addition is to have similar changes of angles for the diagonal angles (NE, SE, SW, and NW to use compass directions).

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/improve-rendering-of-link-arrows-pointing-to-nodes/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
