### ISSUE TITLE
Improve Search Results window

### ISSUE THREAD

**Issue by mario-g** [CompendiumNG/CompendiumNG#124]
Search Results is affected by some problems, ordered by how they are annoying (descending):
- "insert into view" should let user select where to put the selected nodes, to grab some nodes from a view and put them in another view, or it should be not modal, to let the user select the view in which to put the selected nodes
- default size too small

These problems would be tougher to solve:
- absence of columns to sort by other values
- search should be dynamic: merge "search" and "search results" functionality and drop "search again" button

**Comment by SebastianBoell** [comment]
There are actually a number of good suggestions regarding improving the search including results and the actual search itself. It may be a small project to consolidate these ideas and work on a redesign of the search and the results display :)
Keep fingers crossed my review of the feature suggestions continues as fruitful as the last few days and I should be able to hand a complete list of suggesions on this by mid March.

**Comment by mike223** [comment]
To got further on we could integrate search and filtering. 
There are some ideas on filtering at the end here: https://github.com/CompendiumNG/CompendiumNG/issues/6

The filtering could be an alternative to a special search window: 
Have a map or list that automatically contains all nodes. Use the filter (that is a functionality of usual maps too) on the content. Modify, copy or delete the remaining nodes you want to work on directly. 
This way we could avoid having a seperate user interface for searching. And one could use all the functionality of usual maps or lists: read the details, directly change the label, see linked bitmaps, see links between nodes, have access to the tags, create date, author and containing-this-one-maps. 
With the possibility to save a filter as a node we could have dynamic maps based on contents. 
This could be the long needed additional principal benefit of Compendium over a file system. (The first two benefits being that the x-y-position of things and links between them are saved.)

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/improve-search-results-window/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
