### ISSUE TITLE
Mass linking features

### ISSUE THREAD

**Issue by mario-g** [CompendiumNG/CompendiumNG#125]
There are some useful features missing:
- A) Delink a group of selected nodes (now only one node can be delinked at a time)
- B) Link all nodes to another by selecting them, clicking "link to..." and selecting the following node. This is a time-based action, executed in three steps. It would be easier to implement for example by 
- C) Deselect nodes or links only from a selection of nodes and links, obtained for example by alt-clicking a node (which selects dependent nodes). This is useful for selecting links or nodes and operate on them
- D) invert link (of a single or more links selected)

**Comment by SebastianBoell** [comment]
for easier commenting I added A-D in the original:
A) This is actually possible: select all the nodes that you want to unlink; hold shift, right click and select delink
B) See also an earlier similar suggestion: http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=313
C) Not sure how this is playing out in contrast to the current option of holding down the shift key for adding and removing single links and nodes to a selection?
D) This is already possible: select a link and in the link toolbar change 'From-To' to 'To-From' or vice versa

I set this to 'minor' as A, C and D seem to be already existent. B) would be nice to have, but in terms of priorities I think 'minor' is justified for now.

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/linking-multiple-nodes-to-another-node-at-once/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
