### ISSUE TITLE
Make a node or map read-only

### ISSUE THREAD

**Issue by mario-g** [CompendiumNG/CompendiumNG#126]
Sometimes nodes can be deleted or modified unintentionally, so it would be very useful to implement a simple lock.
For nodes, it prevents editing contents. For containers, it prevents moving, relinking, rearranging, adding and deleting nodes inside the container.

**Comment by SebastianBoell** [comment]
I added 'map' to the description to capture that aspect of this suggestion as well.

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/make-a-node-or-map-read-only/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
