### ISSUE TITLE
Possibility to drag windows outside the screen as in Compendium 1.5.2

### ISSUE THREAD

**Issue by mario-g** [CompendiumNG/CompendiumNG#128]
In Compendium 1.5.2 it was possible and very useful to be able to drag windows outside the screen. In Compendium 2 this is not possible anymore.

**Comment by SebastianBoell** [comment]
Setting this as minor for now. May be good to evaluate if this feature is missed by other users as well. Generally I think we should think about the ways in which navigation between maps can be done more efficiently than it is currently possible.

**Comment by maiklos** [comment]
fixed this since it is annoying. Map navigation problem still remains, but it is not better or worse after removing this limitation.
