### ISSUE TITLE
audio feedback delays operations

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#13]
you can enable audio feedback "tools" -> user options -> audio & zoom

problem is that "audio play" happens in the same thread.

reproduce:
1) have a map
2) create map node
3) enable audio feedback "tools" -> user options -> audio & zoom
4) double-click the map-node
5) first audio is played and then the node is opened. When I disable audio feedback then the node is opened immediatelly

proposal: move the audio play into a dedicated thread

**Comment by maiklos** [comment]
problematic method is playAudio in UIAudio which 1) start the clip in extra thread 2) wait for predefined time 3) stops the clip 

waiting should be moved into the playing thread so the main thread is not blocked

**Comment by SebastianBoell** [comment]
Agree that the delay is not nice. Generally I wonder if the audio feedback is something important to contain in Compendium. Overall I would suggest trying to strip back Compendium whereever possible to create a nice and clean interface and interaction, maybe not for M1 which may mainly push Compendium 2.0 beta to a stable first release. But for a respective next release of CompendiumNG. Of course  when requested or when it seems necessary we can slowly upgrade/reintegrate features?

**Comment by maiklos** [comment]
ok, agree. 
solution will be to remove audio feedback feature.

**Comment by maiklos** [comment]
fixed in ab5bb9e97caa0bc859abf1534909c30ad347c719
