### ISSUE TITLE
portable edition

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#131]
1) installer should allow to install in a portable way:
a) don't relay on user home dir for setting and allow for auto-search or override from a start script
b) portable launcher ?

**Comment by SebastianBoell** [comment]
I think if users can easily specify their data directory and if CNG can scan for projects in there automatically it may be good enough if users can put their data into a cloud and then refer to this location from different machines?
Also if the data directory is scanned for projects automatically and as now projects are saved in different folders it is now much more easy to copy projects via USB between machines.

In addition a purely mobile edition as indicated here may makes sense. It may install CNG into a directory with three sub directories: 
*application
*data
*settings

**Comment by maiklos** [comment]
CNG is dependant on administration database. I am not sure if it would be feasible to remove it.
However for this issue I was thinking something easier as allow to override location of settings (which can't be stored in user home directory in portable edition) to application location (alternativelly it could be autodetected).
This would allow to run in one directory stored on a flash disk i.e.)

**Comment by maiklos** [comment]
I've made some change in order to make CNG able to run in portable fashion. (see wiki pages: CompendiumNG-installer and "configuration" for details). Have to add some more start scripts yet.
