### ISSUE TITLE
scrolling of maps using the mouse wheel

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#133]
The zoom feature using CTRL and the mouse wheel is great. Howevever, during it's implementation it became impossible to use the scroll wheel for simple scrolling in a map. I know we want to imporve panning in general, but I suspect that a number of users may miss the abilit to scroll using the mouse wheel which used to scroll vertically in maps but now does nothing.

I suggest to follow the "standard" for using the mousewheel (e.g. Incscape or GIMP):
- mouse wheel scrolls vertically;
- SHIFT + mouse wheel scrolls horizontally.

I set this to 2.1.2 as I think it would be good to fix for the first stable 2.2 release.

**Comment by SebastianBoell** [comment]
I just started working with the improved panning and I think this issue here is no longer needed and can be closed.

However, I suggest now tp associating the zoom feature with the mouse wheel WITHOUT having to press CTRL. This way moving around the map and zooming in and out can be done without the need of using the keyboard.

Over all I think this tremendously improve user interaction in 2.1.1 in comparison to any prior versions of Compendium. It is one of those things where people cannot believe how working without them was ever possible. I believe this will convince many to switch to CNG!

**Comment by maiklos** [comment]
as you wish :-)
