### ISSUE TITLE
Performance drop from 2.0beta to 2.1.1?

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#144]
I just exported my database from 2.0 and imported it into 2.1.1 when I noticed a makedly difference in performance when opening complex maps (150-250 nodes). In 2.0 beta the maps open in about 3 seconds, whereas it takes about 30! seconds under 2.1.1. I don't know what may be the cause of this problem, but I think this is something we should investigate a bit closer as the difference is a whole order of magnitude.

I mark this for now as a general bug. Would be good to look at as part of our first stable release (set to 2.2). Let me know if you like a copy of the database in question, but I guess any project will do.

**Comment by maiklos** [comment]
can you try to decrease logging severity ? ... in: ~/compendiumng_config/log4j.properties:
...=DEBUG    -> ...=ERROR

**Comment by SebastianBoell** [comment]
I reduced logging severity even down to 'info' but it seems to make little to no difference. 

In direct comparison C2.0b is much more responsive when opening maps than CNG2.1

**Comment by maiklos** [comment]
do you mean opening map icon - not the whole project right ?
if you open the map second time in the same session is it faster ?

**Comment by SebastianBoell** [comment]
Absolutely, that is what I mean. I also thought it may be possible to pre
buffer maps after startup?

**Comment by mike223** [comment]
No difference in performance between 2.0 Beta 1 and 2.1.1 for me.
(Compendium 2.1.1, java-6-sun, mysql-server-5.1, imported database from 2.0 Beta 1, Ubuntu 10.10)

**Comment by SebastianBoell** [comment]
This then points into the direction of Derby as the reason for the performance difference.

**Comment by maiklos** [comment]
we need to retest this issue with new version 2.1.3. I am moving this issue to 2.1.4 in case some more improvements are needed.

**Comment by maiklos** [comment]
can we still reproduce this with current version (2.1.5) ?

**Comment by SebastianBoell** [comment]
I will test performance with a big file and post loading time for 2.0 beta and 2.1.5

**Comment by SebastianBoell** [comment]
I testes opening speed of CNG and opening and switching larger maps. In both case I could no longer observe performance differences between Compendium 2.0 beta and CNG 2.1.5. I will close this issue now.
