### ISSUE TITLE
Compendium connecting to OpenUniversity at startup

### ISSUE THREAD

**Issue by mike223** [CompendiumNG/CompendiumNG#145]
After starting Compendium 2.0 Beta 1 (on Ubuntu) connects to a web server of the Open University:

GET /institute/download/version.txt HTTP/1.1
Cache-Control: no-cache
Pragma: no-cache
User-Agent: Java/1.6.0_26
Host: compendium.open.ac.uk
Accept: text/html, image/gif, image/jpeg, _; q=.2, */_; q=.2
Connection: keep-alive

Packets were captured with Wireshark. 
There might be a real benefit for the user which I just do not know. 
But the reason for this functionality could be to monitor the use of the software, too. 
When the connection to the server is not possible, but not without network at all, the startup of Compendium is delayed for about a minute waiting for the connection. 

If there is no very good explanation for this spyware-like functionality I'd like you to get rid of it.

Mike and his 15k Nodes

**Comment by SebastianBoell** [comment]
I think it would be good if you could check if the OpenUniversity connection issue is also existend in CNG 2.1.1 onwards.

**Comment by maiklos** [comment]
I think I have disabled it long time ago but I will doublecheck

**Comment by SebastianBoell** [comment]
Thanks Michal. I think in general such a functionality will be good if we want to enable auto update checks or sharing of maps through a cloud in the future. 

I can recall a discussion on the Compendium mailing list where Michelle mentioned that this was initially created for auto update checks.

**Comment by maiklos** [comment]
It was removed/fixed earlier. I have checked with Wireshark and can confirm that CNG is not trying to connect during start up to any website.
