### ISSUE TITLE
Arrange-Function aligns nodes in a wrong way

### ISSUE THREAD

**Issue by mcomp** [CompendiumNG/CompendiumNG#146]
There's a problem with the "Arrange" function (View --> Arrange): "Left to right" and "Top-down" seem to be mixed up, because when using for example "Left to right"  in a map to align the containing nodes one gets a "Top-down" alignment, and vice versa.

**Comment by mike223** [comment]
Running Compendium 2.0 Beta 1 on Ubuntu

**Comment by maiklos** [comment]
I've swapped it so arrangement is done in accord with menu items. Internally the arrangement classes remains named incorrectly

**Comment by mcomp** [comment]
Thanks!
