### ISSUE TITLE
Help on Inbox goes to the wrong page

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#153]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=905

Mario Valle 2010-07-06 16:03:34 BST

Activating "Help on Item" and clicking on the Inbox puts you on the Nodes->View
help page that does not mention Inbox anywhere. Instead a better page is
Accessibility -> Group Working.
Hope it helps
mario

**Comment by maiklos** [comment]
I have such a strong feeling that we had this issue already ;-)
From what I remember when I have been investigating this issue: 
inbox is actually a list view so the help page where help is directed is correct though not very logical.
I think the simple way would be to add help on inbox text to that particular section of help. Changing
the would mean too extensive changes that IMO don't worth of doing considering severity and impact of this issue

**Comment by SebastianBoell** [comment]
I agree with you that this is maybe beyond minor. I think we can close it and maybe re-visit all issues related to a 'Help on item' functionality when we are re-doing the interface in 2.8. -- So alternatively this issue may go there as well. I leave this up to you.

**Comment by maiklos** [comment]
closing in favour of #157
