### ISSUE TITLE
Cut-Paste does not need embedding warning

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#154]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=904

Mario Valle 2010-07-06 08:18:02 BST

If I Cut a node in a Map and then Paste it in another Map, I receive the
warning popup that remembers me that "The node is actually an embedding... use
Clone...".
I think the warning should not appear for Cut-Paste (no node duplication), but
only for Copy-Paste (node duplication).
Hope it helps
mario

Comment 1 Michelle Bachler 2010-07-06 22:12:54 BST

OK. I'll look into it. I have a feeling that at the point of paste I currently
don't know whether it was a cut or copy, but I am sure I can code it so I do.

Michelle

**Comment by SebastianBoell** [comment]
I think this can be consicered a bug as when using cut and paste clone makes no sense as the original to be 'cloned' is usually removed through the 'cut' operation.

**Comment by maiklos** [comment]
I don't know how to reproduce this behaviour. Neither copy nor cut show such pop-up message.
Also I wasn't able to find such message anywhere in the source code. It seems to me this has been removed already.

**Comment by SebastianBoell** [comment]
I even tried in 2.0 beta, the version for which it was originally reported and have a hard time reproducing this behavior. As there is also no trace of this message in the code I will close this issue.
