### ISSUE TITLE
QuestMap import issues 

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#155]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=394

Al Selvin 2006-12-31 23:39:24 GMT

When importing QuestMap files, Compendium does not unescape quotations. For
example, a QuestMap node

Entered: 20 Oct, 2003  Modified: 20 Oct, 2003
with the name:
Earvin "Magic" Johnson

is exported as:
"Earvin \"Magic\" Johnson

When Compendium imports this file, it creates a node with the name:
Earvin \"Magic\" Johnson

22.When you import from QuestMap, the dialog box to select the file to import
has two problems that cau

Entered: 10 Dec, 2002  Modified: 17 Feb, 2005
1) it doesn't remember the last file name you imported, so if you use the same
one over and over you have to select it again every time

2) it displays way over in the upper left of the screen, so you have to mouse
all the way over there from the center every time. It should be centered like
other dialogs. - FIXED

(from old db, low list)

**Comment by SebastianBoell** [comment]
I classified this as a minor bug as the import function does not work as can be expected.

**Comment by maiklos** [comment]
do we have some QuestMap file so it could be re-tested ?

**Comment by SebastianBoell** [comment]
Good question, I mainly put it here for completeness sake. Tried to google QuestMap and could not find it. It seems to be not a major player. IMO we should focus on major applications for improving and extending import/export. I think we can close this as 'wontfix'.
