### ISSUE TITLE
Implement a scrollabel desktop 

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#156]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=805

Description Michelle Bachler 2009-09-15 15:34:19 BST

see item 48. Code in UIDesktop and UIDesktopManager (commented out).
There where issues with internal frames larger than the visible desktop and
scrolling which meant if you scrolled up, it always moved you down again. Alos
some general paint bugs on the Mac.

Needs coming back to, so separated from item 48, as that item was satisifed
with other code.

**Comment by SebastianBoell** [comment]
This report is a bit cryptic, but it points to a particular place in the code that has to do with scrolling the CNG 'desktop'. Issue 48 in Bugzilla is dealing with scorllable desktop (http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=48). As this may be platform specific we can consider closing this issue right away and see if something comes up again in the future. Anyway with version 2.8 this may become obsolete when we rework the UI.

**Comment by maiklos** [comment]
well IMO just description of this issue: "Implement a scrollable desktop" is what is needed.
IMO it is rather feature request that should really go to to 2.8 unless someone is convinced that it is too much a bug with <2.8 versions

**Comment by SebastianBoell** [comment]
I agree, this is better classified as a feature. From looking at issue 48 on bugzilla, I think the need for a scrollable desktop was to revover "lost" windows. Generally I think this feature does not sound like a good idea as it can contribute to confusion if "windows" are on funny places on the CNG desktop. For now I can't see how having a scrollable desktop has any major advantages that would justify this.

IMO this issue can be closed. I already marked it accordingly. If you agree please close.
