### ISSUE TITLE
problems with icons on Mac

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#161]
Mac users report problems with icons on Mac.

see discussion here: http://compendiumng.org/topic/initial-comments/

**Comment by SebastianBoell** [comment]
Re-reading the user report:

"I also found the changed icon colours a bit jarring – being used to the more colourful compendium 2 defaults."

 It therefore seems that this could be due to the icon theme change and therefore may be resolved with #168

**Comment by maiklos** [comment]
I have changed the icons back to default (in #168) so Mac users should be also more happy now.
