### ISSUE TITLE
Dev team information

### ISSUE THREAD

**Issue by mike223** [CompendiumNG/CompendiumNG#164]
"Hmm. Two guys took over development of Compendium from the Open University: Michal Stekrt and Sebastian Boell. Don't know them. Not much information. Not much from them to be found in the old Bugzilla either. Let's wait ..."

Not what you want ?

You took over development but I feel that it would be a good idea to give some information on 
- Why do you work on Compendium at all ?
- Do you get payed for ?
- How much did and do you use Compendium yourself ?
- What are your goals for Compendium ?
- Anything else ?

either here on on compendiumng.org. 

It would be nice if you make it easy for the users to trust you. At least if you are interested in people
- using CompendiumNG
- reporting bugs
- supporting your work

Mike and his 15k nodes.

**Comment by maiklos** [comment]
this is neither bug nor feature request. Please post it into forum instead.

**Comment by SebastianBoell** [comment]
Michal and I are both working on this in our spare time besides our full time jobs and private life. There is a plan to have a bit more detail on the development on our website as soon as I have time to write something propperly on it :)

**Comment by SebastianBoell** [comment]
We have added most of the details you asked for on our website (see #168).

**Comment by mike223** [comment]
I hope such information might help people understand why you work on CNG. In order to build enough trust for others to take over responsibility too. 

It looks like there might be a typo above: #178 instead of #168.

Btw: I could not reach http://compendiumng.org/ for some days now.
