### ISSUE TITLE
Different version numbers 2.1.1/2.1.2

### ISSUE THREAD

**Issue by mike223** [CompendiumNG/CompendiumNG#165]
I got the download from here:
http://compendiumng.org/downloads/CompendiumNG-installer-2.1.1.jar

After installation the information in menu Help, About...
shows "Version 2.1.2"
Could lead to some complication with bug reports mentioning a wrong version number.

Which one is it really ?

**Comment by maiklos** [comment]
It is 2.1.1 by mistake it says 2.1.2. It is fixed in version 2.1.2 (which hasn't been released yet) and which says: 2.1.2
