### ISSUE TITLE
Missing icon for Inbox

### ISSUE THREAD

**Issue by mike223** [CompendiumNG/CompendiumNG#167]
The icon for the Inbox in the Home Window is the "missing link" one, with two question marks on grey ground, separated by a white zig-zag line. 
In the outline view the old, small version of the blue Inbox icon with "IN" is being shown. 

Mike and his 15k nodes.
(Compendium 2.1.1, java-6-sun, mysql-server-5.1, imported database from 2.0 Beta 1, Ubuntu 10.10)

**Comment by maiklos** [comment]
there is wrong path to the icon. as a workaround you can fix it yourself, by selecting changing path in the inbox properties to lead to the right icon.

**Comment by maiklos** [comment]
I have checked the code and it seems to me that the path to the inbox icon is correct in the default project. I suspect that the problem with inbox icon only happens when you open/import map created or saved with older version of Compendium (or CompendiumNG). In that file there is probably path to the old location (System/......). Can confirm this ?

**Comment by mike223** [comment]
You are right:
INSERT INTO ReferenceNode (NodeID, Source, ImageSource, ImageWidth, ImageHeight) VALUES ('1...','','System/resources/Images/inbox.png',0,0)
Should be no problem to replace the string. 
What should the new location be ?

**Comment by maiklos** [comment]
should be: images/inbox.png 

I will log ticket for import so transfer to CompendiumNG is more smooth

**Comment by scribbly** [comment]
I realise that this issue is closed, but just wanted to mention that the icon for my inbox is broken too, and that's after a clean install.

**Comment by maiklos** [comment]
can you describe steps ? 
what is the path to the icon - when you check the inbox properties ?

**Comment by scribbly** [comment]
Steps to install? Just the standard on Win7 64.

I couldn't get the properties window to open for me: Insert should work when highlighted?

I also noticed that the List Node icon was displayed in the Search window.

I'm not at home at the moment, but can check later tonight if you want further clarifications.

**Comment by SebastianBoell** [comment]
I can also add that you cannot access the properties for 'trash bin' or 'inbox' for some reason. This was already so in Compendium 2.0.

**Comment by maiklos** [comment]
I think this is intended behaviour

**Comment by maiklos** [comment]
version 2.1.3 should handle icon location in more robust way so problem with missing icon for should not appear anymore.
