### ISSUE TITLE
Difficulties due to change of default icon set in 2.1.1

### ISSUE THREAD

**Issue by mike223** [CompendiumNG/CompendiumNG#168]
The default icon set was changed from Default to eDance. This could make it harder to get started, a least as long the help contents is not changed accordingly:

"Mandy just installed Compendium for the first time. She looks for menu Help, Help contents. But all the examples look different from what she produces in front of her. She is somewhat confused."

I'd prefer this change to be postponed until the help can be changed too. At the moment the help contains mostly "Default" nodes and some from an even older icon set. The same might be true for other documentation. 

I would suspect for beginners a color coded icon set like "Default" would be easier to get started.

**Comment by maiklos** [comment]
well, it was not intentional change. I will change it back in next release.

**Comment by maiklos** [comment]
changed the icons back to Default in b93878a
