### ISSUE TITLE
Links from external software

### ISSUE THREAD

**Issue by mike223** [CompendiumNG/CompendiumNG#169]
Compendium will be able to take a server/database/project/map/node-ID-combination from the command line and as an URL. After starting or while already running it opens the map and marks/centers the node. There could be a second mode which directly opens the resource a choosen reference node points to. 

"From time to time Sarah uses other software than Compendium. The annoying thing being that Compendium wants to be the master: It gives commands to open websites, files and programs. But it refuses to accept any commands from other software. E.g. there is no way to have her todo-list in a text editor with a link to a specific map in Compendium. She hates that she is locked in: Either she uses Compendium as the center for organising her work. Or she would need to search for the corresponding node in Compendium herself every time."

This is one important feature in order to make Compendium more useable in everyday work.

**Comment by SebastianBoell** [comment]
Thank you mike223 for this suggestion. I think this would be especially helpful when collaborating with others as you could send then a link to something within CNG.

We are actually aiming to improve CNG in this regard to make it receptive for commands. Your suggestion is therefore part of a bigger thing to make Compendium in general scriptable, programable and accessable through an API. Hence for now I mark it as minor. As soon as CNG is reworked to be more modular and prepared for scriptability, etc. this should be straight forward to implement.

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/enable-linking-into-compendium/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
