### ISSUE TITLE
merge in hotfix from Michelle (2.0 Beta-NE)

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#170]
merge in hotfix from Michelle (2.0 Beta-NE)
...
OK, I found 2.0 Beta 1 and 2.0 Beta-NE on my subversion and I diffed them.
The only differences where to fix the XML export bug in:

io/xml/XMLExport.java line 1207

was:
table.put((Object)linkViewID, (Object)link);
changed to:
table.put((Object)linkViewID, (Object)linkProps);

And the same fix in
Io/xml/XMLExportNoThread.java line 1194
was:
table.put((Object)linkViewID, (Object)link);
changed to:
table.put((Object)linkViewID, (Object)linkProps);

That’s it.
Both changes are in the final release I put out:

http://compendium.open.ac.uk/subversion/public/Compendium/Compendium-v2.0-Beta2-In-Progress/

Michelle

**Comment by SebastianBoell** [comment]
I think she include the fix of the 'window gets stuck on top bug' #49 In this case the code may be already included in CNG.

**Comment by maiklos** [comment]
this has something to do with export - its' unrelated to #49

**Comment by maiklos** [comment]
I have checked the code and find out that modification are already applied to the source code of CNG.
