### ISSUE TITLE
zooming occurs while wheeling without Ctrl

### ISSUE THREAD

**Issue by wilderny** [CompendiumNG/CompendiumNG#172]
I have installed CompendiumNG on Linux Ubuntu 12.04, and I was surprised to discover that touchpad "mousewheel" (right side of the touchpad area normally used for wheeling) produces zooming. This makes the application impossible to use.

Meanwhile, zooming does NOT occur when I do wheeling with Ctrl, Shift, Alt or any other combination of buttons.

I know that this is not expected, as the zooming should work only when Ctrl is pressed. Let me know if you need any additional information.

**Comment by SebastianBoell** [comment]
Given the comment I think we should stick to the common “standard” (e.g. Scribus; GIMP, Incscape) for zooming and panning:

mouse wheel = horizontal scrolling
mouse wheel + SHIFT = vertical scrolling
mouse wheel + CTRL = zoom

**Comment by maiklos** [comment]
implemented as suggested by Sebastian - please test it

**Comment by SebastianBoell** [comment]
Great work. All works now like a charm and according to standards. This issue can be closed now.
ps.: I also updated our list of changes in 2.1.2 page

**Comment by maiklos** [comment]
glad to see you happy... happily closing :-)

**Comment by SebastianBoell** [comment]
More so let's hope that our users are happy with it as well. :)
