### ISSUE TITLE
Issue with Search results Window

### ISSUE THREAD

**Issue by mcomp** [CompendiumNG/CompendiumNG#173]
After performing a search in Compendium 2.0 Beta 1 the Search Results Window cannot be minimized, i.e. the user cannot switch to other already opened maps without having to close the Search results window first and restart the search later. This is quite cumbersome because although the Results window size can be decreased, simultaneous working in other maps is disabled.

**Comment by maiklos** [comment]
search result dialog can be minimized or put aside now.
