### ISSUE TITLE
Reference Files Icons are not correctly displayed

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#177]
When reference files are added to CNG special icons should be used for different file types. E.g. TXT, DOC, PDF, XML, etc. (The default project contains a list of examples)

Currently these icons are not displayed instead the CNG standard symbol for reference files is used. The icons are all there under 'images/ReferenceNodeIcons/' Maybe a upper case lower case issue?

**Comment by scribbly** [comment]
This does not work on my Win7 machine either (so doubt it's a case issue?)

I just wanted to add though, that it would be nice if they could be defined as part of the icon set; maybe as an optional subset, so if it exists it is used in preference to the default?

**Comment by maiklos** [comment]
IMHO best would be to use icons that are used by underlying system. This way we don't have to deal with particular icons, just get it from OS no matter what file type. Also the look of an icon on i.e. desktop would be consistent with icon withinin Compendium.

**Comment by scribbly** [comment]
I agree that using the system icons is useful in some, maybe many, circumstances, but for those who'd like to give their maps a particular look and feel, having the ability to define specific icons / icon sets would be useful (especially if you wanted to group them together: for example you didn't want the distraction of all the different Excel icons and just wanted one icon for the whole range of Excel extensions).

**Comment by maiklos** [comment]
problem is solved now. CNG is displaying icons as defined in ..../images/ReferenceNodeIcons/referencenodetypes.xml. 
Regarding OS icons I have created FSP suggestion: http://compendiumng.org/suggestions/reference-node-icons-from-os/

just a note: currently there is 28 icons defined in CNG for reference nodes.

**Comment by SebastianBoell** [comment]
Working smoothly now. I agree this should ideally be dealt with on a system basis thus reducing CNG code complexity.

Regarding Scribbly's comment. Of course it should be possible for users to define their own nody icons. I think the current way of using 'stencils' is very cumbersome and not straight forward. Also we know that there are many users out there who do not use Compendium for IBIS type of dialogue mapping, which I assume will welcome a more flexible approach to defining node types.

**Comment by scribbly** [comment]
I'm a little confused where discussions about the development are meant to go... I've been putting entries over on compendiumNG, but there doesn't seem to be as much action over there.

Anyway, I added an FSP suggestion http://compendiumng.org/suggestions/allow-map-nodes-to-define-the-ontology/ that I'd hoped would generate some discussion about how to make CNG's maps more flexible (ontology wise). So, apart from ad hoc changes, maps define the ontology, layout rules, icons, links, etc such that if there is not a setting it cascades up to the next parent default.

I guess too if your icons were svg and scalable then allowing non-proportional sizing (via handles) would be neat for mind map type ontologies?

**Comment by maiklos** [comment]
for discussion confusion I want to create some guidelines under #182

**Comment by maiklos** [comment]
reopening:
cng is not trying to display reference icons as defined in reference node types configuration file.

to reproduce:
1) create a reference node
2) in the "content" tab in the "ref:" field type: a.xlsx (this file doesn't exist)
3) confirm and the reference icon remain unchanged

expected behaviour is that excel.gif icon should be displayed instead.
From log file it is obvious that cng is not even trying to load the excel.gif icon.

**Comment by maiklos** [comment]
fixed wrong path for reference node icons

**Comment by ClearBlueSky85** [comment]
Ok reference icons display correctly on 2.1.5 build I tested using Windows 7, however I noticed there were a couple minor errors.

There is an extra file separator for the DIR_IMAGES string, although this didn't seem to matter, and the reference node icons were still displayed.
[ProjectCompendium](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/ProjectCompendium.java) line 329 was:

``` java
DIR_IMAGES = DIR_BASE + File.separator + "images" + File.separator + (isMac?"Mac"+File.separator:"");
```

should be:

``` java
DIR_IMAGES = DIR_BASE + "images" + File.separator + (isMac?"Mac"+File.separator:"");
```

There was another place in the code that used the old way and not the new DIR_XXX string reference.
[UIReferenceNodeManager](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.5/application/src/main/java/com/compendium/ui/UIReferenceNodeManager.java) line 61 was:

``` java
public final static String sFILEPATH = ProjectCompendium.DIR_IMAGES + File.separator +"ReferenceNodeIcons"+File.separator + "referencenodetypes.xml"; //$NON-NLS-1$
```

should be:

``` java
public final static String sFILEPATH = ProjectCompendium.DIR_REFERENCE_NODE_ICONS + "referencenodetypes.xml"; //$NON-NLS-1$
```

Thanks
