### ISSUE TITLE
Add Developers and History section to CNG website

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#178]
In order to further user understanding of the development of CNG I will add a short introduction of the CNG team and earlier supporters of CNG on our website.

Also as part of this I will also expand the 'history' section on Compendium on our website. Create this issue here to actually remind me of doing this. ;-)

**Comment by SebastianBoell** [comment]
Ok thiese bits are done. Can you check if the details are all right. If you think they are fine I will forward this to Simon, Al and Michelle for double checking from their perspective and if we should add any further details on them or anybody else.

http://compendiumng.org/development/

http://compendiumng.org/history/

**Comment by maiklos** [comment]
checked, fixed.

**Comment by alselvin** [comment]
One comment, the installation window should be in tune with the same history (i.e. it still says "Originally developed by the Open University in 2009"). Thanks!
