### ISSUE TITLE
Problem with installing on Windows XP

### ISSUE THREAD

**Issue by TomWaterat** [CompendiumNG/CompendiumNG#183]
FYI.. I installed CompendiumNG on my Windows XP machine - as an Administrator. But when I logged back in as a non-administrator Compendium NG would not start.

I copied the compendiumng_config folder into my 'non-admin' profile - then it initially returned an error when I tried opening a map node.. I logged out and logged back in (as  a non-administrator) and this time it worked fine...

**Comment by maiklos** [comment]
possibly fixed in 1c89426f323e496ffc6f3793d274781909acffd3, need to retest this.
you should install as normal user and installer should raise priviledges - at least it "should" work this way.

**Comment by maiklos** [comment]
version 2.1.3 is behaving more nice. If it can't find user configuration it will create it. This remedies problems you you are reporting here.
