### ISSUE TITLE
migrate stencils/icons to svg

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#184]
Stencils/icons should be replaced with SVG for better scaling.

Also displaying of SVG stencils must be implemented so CNG can work with it.

**Comment by maiklos** [comment]
I have created simple stencil set and also I have traced default stencil set in CompendiumNG/application/src/main/resources/app-rsrc/Stencils-SVG/svg_stencils_master.svg. GitHub can't display svg so displaying just png export)

![svg_stencils_master](https://f.cloud.github.com/assets/251009/522676/a09c5014-c05a-11e2-9f90-3b4603e245a7.png)

simple_1(svg) - should be minimalistic set usable to be printed in small on BW printer
default(bitmap) is import from current version of compendium
default_derived(svg) - is traced and manually adjusted version of default with some svg artwork from open library

**Comment by SebastianBoell** [comment]
Great work!

I jumped in and added a glare to the background to give the icons a more spherec feel:

![text4584](https://f.cloud.github.com/assets/2730822/539940/3928a6fc-c1d2-11e2-92c1-cc5e0718e363.png)

ps.: The way it is currently done may create some 'mist' or 'shaddow' in the exports. If you like the effect I can combine them with the spheres to avoid such problems.

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/migrate-stencilsicons-to-svg/> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
