### ISSUE TITLE
Ref's with URL using https protocol fails to launch

### ISSUE THREAD

**Issue by scribbly** [CompendiumNG/CompendiumNG#185]
for example:

```
https://github.com/CompendiumNG/CompendiumNG/issues/174
```

URL will not launch either by double-clicking on Node or via the Launch button on the Contents tab

**Comment by maiklos** [comment]
problem with the "Launch" button (https) is fixed in f4e686f6009ed3177dc060e6a8bbd9cd0c8ab2cc

**Comment by maiklos** [comment]
already fixed in 23dfca387b12d6b6fd199c3f535e7234c9b96a69
