### ISSUE TITLE
Problem with Map Name when minimized

### ISSUE THREAD

**Issue by mcomp** [CompendiumNG/CompendiumNG#189]
When maps are minimized in Compendium 2.0 Beta 1 their name cannot be read (except for the first two letters). It would be useful to either increase the width of the minimized map bar, to decrease the font size or to have the full name pop up when scrolling over.

**Comment by maiklos** [comment]
the same applies to current version of CompendiumNG. 

we could also consider another solution - to eliminate what is in front of the map name which is currently:

some_space mapicon [Map]: some_space and then there is map_name
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
this could be eliminated and it would save about 50% of the space for map_name

Is the icon and "[Map]" useful at all ? could be there something else than map ?

**Comment by mcomp** [comment]
Yes also a good idea. The icon already suggests that it is a minimized map, so "[Map]" could be omitted

**Comment by maiklos** [comment]
arbitrary [Map]: removed and width of the icons doubled.
