### ISSUE TITLE
Paths to node images lost when creating a new XML template for a custom stencil .

### ISSUE THREAD

**Issue by TomWaterat** [CompendiumNG/CompendiumNG#193]
Hi, I'm using CompendiumNG 2.1.2

When I copied my stencil to a new computer the path for the node image used in the
XML template still referred to the old location of Compendium.. Because compendium was installed on a different location the link with the icons was lost. A solution might be to use relative path names?

See label 'B' in the screen grab attached.

Many thanks in advance.

Regards,
Tom.

**Comment by maiklos** [comment]
in version 2.1.3 paths to stencils are searched for in the stencil directory even for old maps with absolute paths. If there is still some problem in spite of this fix please report again.
