### ISSUE TITLE
Remove solid line border be removed from the custom stencil 'map' node.

### ISSUE THREAD

**Issue by TomWaterat** [CompendiumNG/CompendiumNG#194]
Hi, I'm using CompendiumNG 2.1.2

Can I request that the solid line border be removed from the custom stencil 'map' node?

See label 'A' in attached screen grab.

Cheers,
Tom.

**Comment by maiklos** [comment]
could you pleas add the screen grab ?

**Comment by TomWaterat** [comment]
Hi Maiklos.. See attached, labelled 'A'.

**Comment by TomWaterat** [comment]
Hi Maiklos.. For some reason I can't upload a JPG image.. Essentially if you generate a custom stencil and create a 'Note type = Map' you will see what I mean.  The node has a solid shadowed border around it. If you email me at tom_wb@yahoo.com i can send you the screen grab.

**Comment by maiklos** [comment]
it's project level configurable:
Tools->Project Options->Node Extras->Show Map Border when Map has image
