### ISSUE TITLE
implement new storage format

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#20]
new storage format for InformationBase must be define

characteristics:
when closed it is selfcontained = 1 file
it should support versioning
it must allow storing maps, and documents

**Comment by SebastianBoell** [comment]
- It possibly should also include stencil / user designed icons for nodes.
- Also possibly some settings if it makes sense that they are related to a specific IB. By this I mean specific settings that may be bound to a template. (I guess this will need some further planning and discussion down the road when we have a better understanding of these)

set the type of this to 'feature'

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/improve-storage-format/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.

**Comment by AndreiLeman** [comment]
MongoDB

**Comment by AndreiLeman** [comment]
Also need to redesign this damh Java app to node js. :D
