### ISSUE TITLE
remove movie map node type

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#201]
In the current version we have removed support for movie maps.

This change is reflected in the help file already where all references to movie maps are removed.

However there are still refernces to movie maps in the UI:

1) The node cration tool bar still has a movie map symbol on it. 
2) Right click 'create node' allows to create a movie map node.
3) Right click 'change node' allows a node to be changed to a movie map node.
4) The keyboard shortcut 'O' creates a movie map node.

I recommend that any remaining references to movie maps in the UI should be removed as CNG currently has no build in support for movie maps.

**Comment by maiklos** [comment]
all 4 issues are fixed now. However CNG is still able  to open map that has a movie node already in it. - this is intentional for backward compatibility
Also it is still possible to clone movie node if it already exist
