### ISSUE TITLE
Spammer Control on Website

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#202]
There have been some incidents with spammer registering at the CNG site. Michal has set up a pass question check for sign up but it seems that spammers know their way around it. Two actions need to be taken:

1) establish a capcha or other means that avoids spammers from signing up
2) check the list of registerd users and delete all that are listed as known spammers on publicly listed spammer lists

**Comment by SebastianBoell** [comment]
re 1) I changed the math capcha to an image captcha to see if this makes a difference
re 2) I checked on http://www.stopforumspam.com/search and a number of users appear there but none of them with a red flag. So for now I did not delete these users from our user list as they may be genuine.

**Comment by SebastianBoell** [comment]
The captcha that I just activated for the webpage registration is definitely not working as a number of new registrations just came in. I re-open this issue.

**Comment by maiklos** [comment]
ok, WangGuard in place now. captcha is probably ineffective so I have disabled it. We will se if WangGuard helps.

**Comment by maiklos** [comment]
it blocks now:
![wanguard-stats](https://f.cloud.github.com/assets/251009/1709036/3fa4bd6e-6118-11e3-8541-7648b67c0b74.png)
