### ISSUE TITLE
App name display on Mac should be "CompendiumNG" not "com.compendium.ProjectCompendium"

### ISSUE THREAD

**Issue by alselvin** [CompendiumNG/CompendiumNG#204]
on the menu bar:

![screen shot 2013-11-01 at 8 16 41 am](https://f.cloud.github.com/assets/5830715/1453326/7f807d34-42ef-11e3-92cb-c79ca0b8be57.png)

**Comment by maiklos** [comment]
this is MacOS specific behaviour - it uses class name. see here for details: http://stackoverflow.com/questions/8918826/java-os-x-lion-set-application-name-doesnt-work.

it should be fixed now:

**Comment by maiklos** [comment]
unluckilly this fix causes more seriuos bug so I have to roll it back.
Problem is that the argument that I added to the startup script will result in CNG unable to start at all.

**Comment by maiklos** [comment]
based on http://alvinalexander.com/blog/post/jfc-swing/how-put-java-application-name-mac-menu-bar-menubar I tried to fix the problem in 9ed0600f1c102a9f7aaff95086a755179ba05dc3

**Comment by maiklos** [comment]
one more fix in: a694456b0bd8dede8aa1b8b66c44ca30a85355d7. Need to test it
