### ISSUE TITLE
Could not resolve org.gradle.api.plugins:gradle-izpack-plugin:0.2.1

### ISSUE THREAD

**Issue by joe312213** [CompendiumNG/CompendiumNG#209]
on 64bit win 8.1, running gradle 1.9 rc4, with JAVA_HOME correctly set, I get the following every time trying to build CompendiumNG 2.1.3:

C:\Users\Joe\Documents\dev\CompendiumNG>gradle

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'CompendiumNG-parent'.
  
  > Could not resolve all dependencies for configuration ':classpath'.
  > Could not resolve org.gradle.api.plugins:gradle-izpack-plugin:0.2.1.
  >  Required by:
  >      :CompendiumNG-parent:unspecified
  > Could not GET 'http://repo1.maven.org/maven2/org/gradle/api/plugins/grad
  > le-izpack-plugin/0.2.1/gradle-izpack-plugin-0.2.1.pom'.
  >      > Connection reset
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED

Total time: 8.324 secs

gradle -v returns:

C:\Users\Joe\Documents\dev\CompendiumNG>gradle -v

---
## Gradle 1.9-rc-4

Build time:   2013-11-18 09:32:42 UTC
Build number: none
Revision:     7970ec3503b4f5767ee1c1c69f8b4186c4763e3d

Groovy:       1.8.6
Ant:          Apache Ant(TM) version 1.9.2 compiled on July 8 2013
Ivy:          2.2.0
JVM:          1.7.0_25 (Oracle Corporation 23.25-b01)
OS:           Windows 8 6.2 amd64

C:\Users\Joe\Documents\dev\CompendiumNG>

**Comment by maiklos** [comment]
http://repo1.maven.org/maven2/org/gradle/api/plugins/gradle-izpack-plugin/0.2.1/gradle-izpack-plugin-0.2.1.pom seems to be available now. IMHO it was some temporary network problem. 

also git commit 7970ec3503b4f5767ee1c1c69f8b4186c4763e3d is not in CNG repository
I have upgraded gradle wrapper to 1.9 and gradle-izpack-plugin to 2.1.3 in cffc324d337e92421831caadd628aad080cd8c70. It was built succesfully on Cloudbees CI server so I believe it should build for you as well. Could you please retest it ?

Thx
Michal

**Comment by maiklos** [comment]
with the latest builds I haven't experienced this problem. I believer it is not issue so closing it.

**Comment by joe312213** [comment]
Hi Michal,

Thanks for the heads up. Yes I could build it now. Although after
installation when I try to run CompendiumNG I get the error in the
attached. Is it worth filing another bug report about?

Happy New Year!

Joe

On 9 December 2013 19:07, Michal Stekrt notifications@github.com wrote:

> http://repo1.maven.org/maven2/org/gradle/api/plugins/gradle-izpack-plugin/0.2.1/gradle-izpack-plugin-0.2.1.pomseems to be available now. IMHO it was some temporary network problem.
> 
> also git commit 7970ec3https://github.com/CompendiumNG/CompendiumNG/commit/7970ec3503b4f5767ee1c1c69f8b4186c4763e3dis not in CNG repository
> I have upgraded gradle wrapper to 1.9 and gradle-izpack-plugin to 2.1.3 in
> cffc324https://github.com/CompendiumNG/CompendiumNG/commit/cffc324d337e92421831caadd628aad080cd8c70.
> It was built succesfully on Cloudbees CI server so I believe it should
> build for you as well. Could you please retest it ?
> 
> Thx
> Michal
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CompendiumNG/CompendiumNG/issues/209#issuecomment-30162643
> .

## 

---

http://pepol.net    http://www.healthylovingrelationships.com
http://www.tangolingua.com

## _recommended:_ http://350.org   http://ted.com
