### ISSUE TITLE
[Type: Other] Minor typo error in Download Windows page content

### ISSUE THREAD

**Issue by pcuttriss** [CompendiumNG/CompendiumNG#210]
Hi

Page: http://compendiumng.org/download-windows/

Section: Windows specific instructions

Current text: Please also do a first rung of CNG    (error in 'rung')
Change to:   Please also do a first run of CNG      (correct to 'run')

Regards

Paul Cuttriss

**Comment by SebastianBoell** [comment]
Thanks for the notification, have corrected the typo right away.

**Comment by pcuttriss** [comment]
No probs Sebastian

Thanks for your work maintaining the site.

Paul C
