### ISSUE TITLE
[Type:Other][Level:Minor] Download link for Gradle goes to Maven for Windows build instructions

### ISSUE THREAD

**Issue by pcuttriss** [CompendiumNG/CompendiumNG#211]
Page
https://github.com/CompendiumNG/CompendiumNG/wiki/Download%2C-build-and-run-CompendiumNG---detailed-Windows-instructions

Section
Gradle

Download link currently set to:
http://maven.apache.org/download.cgi

I believe this should point to:
http://www.gradle.org/downloads

Regards
Paul Cuttriss

**Comment by maiklos** [comment]
thanks, fixed
