### ISSUE TITLE
Search results is showing unreadeble results

### ISSUE THREAD

**Issue by gunnare** [CompendiumNG/CompendiumNG#213]
Searching>Type/Tags
Searching for anything in my Maps, gives as a result some unreadable text.
I have got the latest version.

![search result](https://f.cloud.github.com/assets/6851664/2322145/5c009ca8-a3ad-11e3-883d-191dc375cc80.png)

**Comment by maiklos** [comment]
could you please provide some more details ?
version of CNG, and how does the nodes that it finds look like ?

**Comment by gunnare** [comment]
Ni Michael,

If there is anything else I could support you with, please come back. It is an honor to support you and your project to make Compendium even better!

BR

Gunnar Eriksson

Från: Michal Stekrt [mailto:notifications@github.com] 
Skickat: den 6 mars 2014 13:17
Till: CompendiumNG/CompendiumNG
Kopia: gunnare
Ämne: Re: [CompendiumNG] Search results is showing unreadeble results (#213)

could you please provide some more details ?
version of CNG, and how does the nodes that it finds look like ?

**Comment by maiklos** [comment]
could you pls. comment directly in github issue tracker. I can't see anything useful. ... or just send an e-mail.

**Comment by gunnare** [comment]
Hi Michael,

![v212](https://f.cloud.github.com/assets/6851664/2398296/465a1a8a-a9f4-11e3-9079-6b8384ef271a.png)
![clipboard04](https://f.cloud.github.com/assets/6851664/2398306/5600ce8e-a9f4-11e3-88f8-bb9ddc1e8bf0.png)
![clipboard05](https://f.cloud.github.com/assets/6851664/2398310/5b99a30c-a9f4-11e3-906b-5dd1a82f8e72.png)

Sorry didn,t look into github and my graphics seems not to have been included last time.
Suggestion: could it be Swedish that is making it unreadeble? 
If there is anything else I could support you with, please come back. It is an honor to support you and your project to make Compendium even better!

BR
Gunnar Eriksson
