### ISSUE TITLE
Forum Subscription not working

### ISSUE THREAD

**Issue by Ramona-S** [CompendiumNG/CompendiumNG#214]
Hi, 

I'm not sure if this is the right place, but I could not find any better. 

I tried to subscribe for the forum (different user name), but I was not provided with a password. Repetition did not change it.
Maybe somebody could have a look.

Thanks,
Ramona-S

**Comment by maiklos** [comment]
can you send  user id that you used ?

**Comment by maiklos** [comment]
it seems that some domains were not able to receive e-mails due to missing reverse domain  record. I'v fixed it already.

**Comment by Ramona-S** [comment]
Hi Michal,

sorry for delayed reply, was really busy.

Thanks for reply, but I can't provide good news.

I tried to retrieve a new password, because the one I used for
registering did not work. I tried my username (Ramona) as well as my
mail-address, but no new password was sent.

A friend of mine has the same problem (Username: Thoskk), he also does
receive a new password.

Maybe you could have a second look.

Best regards,
Ramona

Michal Stekrt wrote:

**Comment by maiklos** [comment]
It seems there is a problem with delivering email to @gmx.de

is there a chance to use another mail provide ?

**Comment by Ramona-S** [comment]
Hi Michal, Hi Sebastian,

thanks for caring! It worked, I could log in and changed my mail address.

I will tell my friend so he can contact you, Sebastian, as soon as he
got a different mail account. Maybe this could take a while, he's also
quite busy recently.

Thanks again for you help guys!
Ramona

**Comment by ClearBlueSky85** [comment]
Hi I am also having trouble with getting registered to use the forum at compendiumng.org using my gmail.com address.  I have not received the registration email yet.  I tried re-registering, however it says that my email is already registered.  I tried the lost password link, however it returned an error saying that "The e-mail could not be sent.Possible reason: your host may have disabled the mail() function."  Thanks for your help.

**Comment by maiklos** [comment]
Thanks for reporting, we will look into it.

**Comment by maiklos** [comment]
I did some fixing last nigh, could you please retry ? If it says that your e-mail is already used try to "reset password".

**Comment by ClearBlueSky85** [comment]
Hi I am now able to log in with the new word press site at [compendiumng.org](http://www.compendiumng.org/).  I had get an email to reset my password, which was sent to spam, although I am able to log in so I think the update has fixed the issue.  Thanks.

**Comment by maiklos** [comment]
ok, then I am closing this issue

**Comment by Ramona-S** [comment]
Hi Michal,

sorry for my late reply.

Tried to reset my password using my gmx-address, and now it worked fine!
Thanks for fixing!

Cheers,
Thoskk.
