### ISSUE TITLE
quick reference in help menu not working

### ISSUE THREAD

**Issue by ClearBlueSky85** [CompendiumNG/CompendiumNG#215]
When I click on the "Quick Reference (pdf)" under the help menu, the PDF does not open.  I am using Windows 7.  I am able to get it to work if I change the main.properties setting for doc.quickref to the absolute path where the PDF is located (e.g. D:Documents/CompendiumNG/doc/CompendiumQuickRef.pdf)

[main.properties.default v2.1.4](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.4/application/src/main/resources/main.properties.default)

I think the problem might be that the new Help Menu UI thinks that it might be a webpage address rather than a file.  Comparing to the old Compendium it looks like previously they called a file launcher that launched the file with the absolute path.
[UIMenuHelp.java v2.1.4](https://github.com/CompendiumNG/CompendiumNG/blob/2.1.4/application/src/main/java/com/compendium/ui/menus/UIMenuHelp.java)
[UIMenuHelp.java v1.5.3](https://github.com/CompendiumNG/CompendiumNG/blob/release-1.5.3-alpha5/src/com/compendium/ui/menus/UIMenuHelp.java)

I find the quick reference to be handy to look at briefly more so than the help, so I hope that it will remain a feature that does not get removed 

Thanks

**Comment by SebastianBoell** [comment]
I agree that the the quick reference PDF may be useful for some users. However, I suggest to discontinue this for the following reasong:
1) I am not sure we actually have a text document that we can use for updating and creating the PDF.
2) I believe our limited resources are better used for improving and updating the help file.
I therefore suggest to remove all references to the Quick Help file and close this issue. If we can find some volunteer for maintaining and updating the Quick Help file we can re-introduce it.

**Comment by maiklos** [comment]
fixed the problem with opening the pdf reference file in f0c2e9b17bfdc76732622b7213a06d23ac81933e.
