### ISSUE TITLE
mysql db connection setup

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#24]
when setting up db connection (for mysqldb) there is not test button - just "connect". If the connection failse, than error message appears and connections setup disappears. 

this is not very helpful. 

need to put one extra button: "test" so user can test the connection before saving the connection profile
also failure to connect should result in return to the db connection setup dialog - not in disappearing it.

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="https://github.com/CompendiumNG/CompendiumNG/issues/24"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
