### ISSUE TITLE
Search function blocks working simultaneously...

### ISSUE THREAD

**Issue by mcomp** [CompendiumNG/CompendiumNG#240]
In both Version 2.0 beta 1 and Version 2.1.4 after opening the Search function most other actions are blocked, i.e. accessing maps, nodes, etc. It would be preferable to have the search function opened in tab-form, similar to Tags View or Outline View. This would allow continue working simultaneously.

**Comment by maiklos** [comment]
migrated to FSP http://www.compendiumng.org/questions/make-search-result-window-non-modal/
