### ISSUE TITLE
Two suggestions regarding the "Trash Bin"

### ISSUE THREAD

**Issue by mcomp** [CompendiumNG/CompendiumNG#242]
Another one (also versions 2.0 beta 1 and 2.1.4) : It would be expedient to have a "sort"-function for the content of the Trash bin. At the same time, the size of the Trash bin window should be changeable (which it is not, even though the cursor suggests so when touching the edges of the window).

**Comment by maiklos** [comment]
migrated to FSP (http://www.compendiumng.org/questions/sorting-for-content-of-the-trashbin/)
