### ISSUE TITLE
compendium fails to create tables in mysql database

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#25]
when you want to use mysql database for storage then compendium will fail to create tables on mysql version like 5.5.
Compendium is using old syntax:

type = InnoDB   -> engine = InnoDB

**Comment by maiklos** [comment]
fixed in branch issue-22. commit: a385585

**Comment by mateolan** [comment]
This fix works for me. Thanks a lot.
Users should be advised when using new code from commit, that they need to drop and recreate the blank Compendium database that already exists from failed attempts.
