### ISSUE TITLE
Find command can only find Map nodes, no other types

### ISSUE THREAD

**Issue by CalebPetersen** [CompendiumNG/CompendiumNG#256]
I've tried on multiple computers to search for nodes with certain label or detail text, but the only ones that ever show up in searches are Map nodes.  Have tried on multiple operating systems (Win 7 & 8.1) and multiple versions of CompendiumNG, including latest beta.  Running latest JRE.  Noticed bug many months ago but didn't report then.  Thanks.
![error](https://cloud.githubusercontent.com/assets/10248763/5513008/fd6367d6-87a2-11e4-912c-2797e2e42e21.PNG)

**Comment by maiklos** [comment]
I am convinced that the search works ok.
I tested it myself and it is able to find all nodes with "*"

![image](https://cloud.githubusercontent.com/assets/251009/12219033/e1275676-b731-11e5-8a83-3118470e13b9.png)

make sure that you don't have "Map" selected on second tab:

![image](https://cloud.githubusercontent.com/assets/251009/12219068/676b22de-b733-11e5-98ec-38ba70b7ab25.png)
