### ISSUE TITLE
unable to create new topics on online support forum

### ISSUE THREAD

**Issue by ClearBlueSky85** [CompendiumNG/CompendiumNG#260]
I have registered successfully on http://www.compendiumng.org however on the forum page http://www.compendiumng.org/forum/using-cng/ at the bottom it says that "You cannot create new topics" and on my profile page it says "Forum Role: Spectator"

**Comment by maiklos** [comment]
what is your id ?

**Comment by ClearBlueSky85** [comment]
I found I can view "Questions" if I click on CompendiumNG with the house icon, next to the WordPress icon, in the upper left-hand corner, which takes me to dashboard with a gauge icon, and there is a section for questions with a push pin icon
http://www.compendiumng.org/wp-admin/edit.php?post_type=question

However if I go to "Forums" on the main page I am unable to post questions
http://www.compendiumng.org/forum/using-cng/

My user id is ClearBlueSky for the website

My question was if CompendiumNG supported rolling back the derby database if I accidentally deleted entire maps.  I found that I can restore individual items from the trash bin although haven't figured out if I can restore a map with all links connected to each item.  I'm not sure if it would be appropriate to post under "Questions" or "Forums"

**Comment by maiklos** [comment]
Please try now

**Comment by ClearBlueSky85** [comment]
im not able to try it currently since websense content filtering is blocking it and categorizing it as games so i would need to request an unblock and then try it

**Comment by maiklos** [comment]
it is probably working now.
