### ISSUE TITLE
Cannot open Compendium on IMac by clicking Jar file 

### ISSUE THREAD

**Issue by akashko** [CompendiumNG/CompendiumNG#262]
Failed to create database chgadminb see next exception for details
PLease contact Compendium support staff

OS X Yosemite 10.10.4

**Comment by maiklos** [comment]
could you please paste the exception ?
Can't tell too much from this.

**Comment by akashko** [comment]
This is all I have

**Comment by maiklos** [comment]
what exact version of CompendiumNG are you using please ?

**Comment by nathan-artist** [comment]
I think this may be the same issue as <a href="https://github.com/CompendiumNG/CompendiumNG/issues/219">issue #219: unable to create admin db (derby) on Mac</a>. I just installed CompendiumNG 2.1.4 on a Mac running OS X Mavericks 10.9.5 (and Java 1.8.0.60), and I encountered the same problem, as I expect all Mac users do. The solution is in the thread on <a href="https://github.com/CompendiumNG/CompendiumNG/issues/219">issue #219</a>.

**Comment by SebastianBoell** [comment]
As there is no further confirmation I close this issue. If somebody found the same please report back on using the approach reported in #219 as indicated by nathan-artist
