### ISSUE TITLE
Transclusion Indicator is not working

### ISSUE THREAD

**Issue by nmottagh** [CompendiumNG/CompendiumNG#270]
Hi, 

I am experiencing the same behaviour as defined by https://github.com/CompendiumNG/CompendiumNG/issues/236

I can reproduce it using both 2.1.4 and 2.1.5 for both local Derby and remote mySQL databases.
Client: Windows.

If you can tell me a useful flow to try and capture the logs, I will do it ASAP. 

Thanks!

**Comment by maiklos** [comment]
please comment in #236 and don't open a new ticket for the same issue
