### ISSUE TITLE
http://compendiumng.org/ seems to be down again

### ISSUE THREAD

**Issue by MathiasRiechert** [CompendiumNG/CompendiumNG#272]
No bug, just Compendiumng.org seems to be down. Can I get the executables somewhere else?

**Comment by nmottagh** [comment]
I have a copy of latest dev and GA that I can send you. Let me know how. Dropbox?

I hope this project gets reinvigorated. :( What a waste if it doesn't.

**Comment by SebastianBoell** [comment]
Issue #273 is reporting more detail on this so I will close this as a duplicate.

**Comment by OtmaneAzeroual** [comment]
Hallo everybody, i would like to install the program CompendiumNG. Their website is no longer available,  how do i get it, has anyone already an idea. Thank you in advance for your help! B-regards Otmane

**Comment by joevansteen** [comment]
https://github.com/CompendiumNG/CompendiumNG
