### ISSUE TITLE
compendiumng.org IP address is set to my server? why?

### ISSUE THREAD

**Issue by stefanjarina** [CompendiumNG/CompendiumNG#273]
Hello,

just got reported that your domain compendiumng.org is being re-routed to my resume web page.
As I am a owner of IP address as well as PTX DNS records, I assume that this is an issue in your DNS settings.

Please check it with your DNS registrar as well as VPS provider.

more information:
```
# host compendiumng.org 
compendiumng.org has address 31.31.72.244
compendiumng.org mail is handled by 10 wes1-mx2.wedos.net.
compendiumng.org mail is handled by 10 wes1-mx1.wedos.net.

# host jarina.cz 
jarina.cz has address 31.31.72.244
jarina.cz has IPv6 address 2a02:2b88:2:1::53de:1
jarina.cz mail is handled by 20 mx2.zoho.com.
jarina.cz mail is handled by 10 mx.zoho.com.

# host 31.31.72.244
244.72.31.31.in-addr.arpa domain name pointer prod.jarina.cz.
```

We seems to have same VPS provider so best would be to contact them directly.

Thanks,
Stefan

**Comment by SebastianBoell** [comment]
Thanks for reporting this, I hope Michal will be able to sort this out with his provider. I also closed issue #274 which was reporting this as well.

**Comment by SebastianBoell** [comment]
It turns out that we will have to change our internet provider. Unfortunately this may mean that this issue will not be resolved for some more time.

**Comment by TomWaterat** [comment]
Can I suggest that you create a GitHub web page for CompendiumNG? We have just done this for our software and it is extremely easy. [See more info here](https://pages.github.com/)

**Comment by MathiasRiechert** [comment]
I'd like to cite CompendiumNG in a research paper to be handed in for review in the next weeks. However, citing a webpage that wrongly redirects makes the paper (and the software) seem less trustworthy. Is there an update to the website issue?

**Comment by TomWaterat** [comment]
It appears the compendiumng.org web site is still redirecting to another site.. This is also a big problem for me as I have started using CompendiumNG in my organisation.. but without the official web site I cannot convince our IT department to install it on other computers. Unfortunately I may have to look for an alternative software to do the dialogue mapping. @SebastianBoell @maiklos is there any plans to rectify the problem in the near future?

**Comment by joneprice** [comment]
Wonder where this issue stands?

**Comment by maiklos** [comment]
It should be rectified within 24 hours

**Comment by maiklos** [comment]
fixed now. compendiumng.org now lead to nowhere. If accessing it still land you on jarina.cz it is probably DNS cache issue - try later or refresh you cache
