### ISSUE TITLE
Team

### ISSUE THREAD

**Issue by cualigrafo** [CompendiumNG/CompendiumNG#279]
Hi,
I'd like to know if there is now people working to improve CompendiumNG. I am a group facilitator from Spain and I think it is a very good project. 
What is the develpement language you use?

**Comment by SebastianBoell** [comment]
Hi cualigrafo,
I am sad to say that the project is quite dormant at the moment. Michal and I used to work on it a fair bit but I am not a programmer, so all of the coding rested on Michals shoulders. Possibly if we could find a few comitted Java programmers there could be some change? The only minor problem is that the codebase is not written in a modular way which would facilitate collaboration of multiple programmers. But this could be overcome.

**Comment by maiklos** [comment]
I hope noone will mind if I close this issue since it has been answered :-)
