### ISSUE TITLE
fix openjdk support

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#29]
Running CompendiumNG with openjdk creates problems when trying to re-open existing projects. Projects can be created all right, but when trying to re-open them nothing happens. That is the project can be selected for opening but when proceeding nothing happens. This issue is actually a bug that is pre-existing in Compendium v2 already. It is reported for Debian, not sure about other environments. Currently the fix is to run it with native Java the projects open all right.

**Comment by maiklos** [comment]
confirmed on gentoo linux icedtea 6

it seems that problem is when database is being opened while compendium running on openjdk.

added java setting logging into : SHA: 4c77640399f657ed956caacc4905c18ba4c4c07a

**Comment by maiklos** [comment]
after debugging session I tend to believe that it is rather bug in some versions of openjdk. With icedtea7 this problem doesn't occur. Tested with icedtea-bin-7.2.3.3 (works) and icedtea-bin-6.1.11.3 (doesn't work).

**Comment by SebastianBoell** [comment]
The problem really seems to be with openjdk. For the record I looked up the former issue (#869) in Bugzilla: http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=869
