### ISSUE TITLE
Error building application under Ubuntu 20.04

### ISSUE THREAD

**Issue by ghost** [CompendiumNG/CompendiumNG#294]
## Error while building CompendiumNG under Ubuntu 20.04
BUILD FAILED in 6s
CompendiumNG$ ./gradlew

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.16'.

## How I got there
1. sudo apt install gradle
2. git clone https://github.com/CompendiumNG/CompendiumNG.git
3. cd CompendiumNG
4. ./gradlew

Note: I previously confirmed that I have openjdk installed:
```bash
CompendiumNG$ java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
CompendiumNG$ 
```
Thanks.

**Comment by KnowledgeGarden** [comment]
Was there a stack trace? If so, paste it in a public gist and send that
link.

**Comment by ghost** [comment]
Sorry,  I didn't get any stack trace on the screen.   below is all I got on my console.
Please advise if I can provide any other helpful information.

<pre>
CompendiumNG$ ./gradlew

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.16'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
CompendiumNG$
</pre.

**Comment by KnowledgeGarden** [comment]
Try googling the error.
here's one hit
https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2

**Comment by ghost** [comment]
thanks for the find.  I am now trying the recommendations in there.  Will post results.

**Comment by ghost** [comment]
for what it's worth:  here is the stack log I got from gradlew: [gist](https://gist.github.com/Calang-i/db4b9574f470d567686551e38ea4f88f)

**Comment by KnowledgeGarden** [comment]
It is always useful to google error messages. This was not a compendium
error, it was gradel

**Comment by SebastianBoell** [comment]
The issue is most likely you are using open JDK instead of properitary Java. Try removing open jdk from your system then install proprietary Java.

**Comment by ghost** [comment]
FIXED by using `gradle` instead of `./gradlew`
(local installation of gradle, which turns out to be version 4.4.1)

thanks for all the input.  Note: I'm now back into issue #295

**Comment by KnowledgeGarden** [comment]
I would not support an OSS product which requires a non-oss product such as
the late model JVMs from Oracle.
I suspect that's not really the issue here.
