### ISSUE TITLE
Import open Issues from Bugzilla

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#33]
Import all open issues from Bugzilla related to Compendium v2 (currently 101) into GitHub. The purpose is to have all (open) issues in the tracker used for the development of CompendiumNG. When done talk to Michelle to set status in Bugzilla to migrated. The reason is that open issues will no longer be resolved by the KMI and Michelle but here as part of the CompendiumNG development.
Get Issues from: http://compendium.open.ac.uk/bugzilla/

**Comment by maiklos** [comment]
it might be also useful to put reference to the issue in the github issue tracker in the original bugzilla.

btw. any plans how to map issue attributes (like version, system etc.)

GitHub staff seems to be willing to help in situations like this.
maybe useful resource: http://stackoverflow.com/questions/7281304/migrate-bugzilla-issues-to-github-issue-tracker

**Comment by SebastianBoell** [comment]
Will record how issue # correspond both ways (Bugzilla<->GitHub) and if possible also add issue # to bugzilla. Doing it automatically is tempting, however, not too sure how to do this, learning time may be similar to doing it by hand.  Also doing it bit by bit I will try to recreate/confirm issues in CompendiumNGalong the way and if possible add additional comments. This may also help me in dealing with attributes.

**Comment by SebastianBoell** [comment]
Did the first lot today imported all bugs from bugzilla using the filters:
Product: Compendium
Version: 2.0 Beta 1
Status: everything except 'resolved' and 'closed'
severity' category: Bug-Blocker; Bug-Critical; Bug-Major

Result were 11 bugs.

**Comment by SebastianBoell** [comment]
I also started with some form of outline of rules for the issue tracking system which are now in our wiki and which will be updated as I go along: https://github.com/CompendiumNG/CompendiumNG/wiki/Issue-tracking-system

**Comment by maiklos** [comment]
I renamed PM tag to what I originally meant by it PM = Project Management. Shortcut wasn't probably a good idea.
idea was: PM tagged issue is related rather to project organization, process, management, release or distribution management than software bug/enhancement

from wiki: PM - Issue that is marked for completion as part of the next project milestone.

this is probably wrong. Every issue assigned to a specific milestone should be fixed/implemented in that milestone.
I don't think we need explicit tag for it.

also please consider:  OS specific vs runtime specific (JRE version) - should we 
a)generalize  "OS specific" -> "platform specific" ?
or
b) create new tag "runtime specific" ?

**Comment by SebastianBoell** [comment]
Thanks for the clarification. I guess it is then a good thing trying to express these ideas explicitely in the wiki. Generally I try to minimize labels using grand categories instead. I believe a super fine grained categorisation is not really that helpful and can be even more confusing. 

I tinkered around a bit more and came up with an amended colour scheme. The genereal area is now labeled using light blue and red, orange and green can be used to mark the importance of issues. Please have a look and suggest / make adjustment where you belive it is necessary. https://github.com/CompendiumNG/CompendiumNG/wiki/Issue-tracking-system

ps.: I tried to start using red, orange, green labels for some of our issues. I only took a rough guess, please feel free to adjust!

**Comment by maiklos** [comment]
yeah, I think we got into the "tag hell" quite quickly :-)

now if I think about it I would eliminate UI,usability,PM, data storage,legal tags completely.

1) first group: (severity)
I suggest: critical,normal,minor  = red,orange,yellow

2) second: type
bug, enhancement = blue?, green?

3) third group: flow
I would add a tag to tell "this ticket was closed because it was transformed into another 1...x tickets"
In the last comment there should be reference to these tickets.

we might add label "review" for tickets that are under initial evaluation/discussion.
result of initial review must be:
set severity and set type    ... or marked by the process flow tags as closed,..... transformed

**Comment by SebastianBoell** [comment]
Agree! I simplified the labels. We now have:
- Level: critical, genearl, minor
- Type: bug, feature, other (to mark issues that are neither a bug or feature, such as project management)
- flow: I now inculde 'superseeded' to mark issues that have been replaced; and 'needs review' for issues that will need to be looked at.

https://github.com/CompendiumNG/CompendiumNG/wiki/Issue-tracking-system

ps: I also added 'Type' and 'Level' to the labels to somewhat provide a sorted list on the left side in the issue system.

**Comment by SebastianBoell** [comment]
Did the second lot today imported all bugs from bugzilla using the filters:
Product: Compendium
Version: 2.0 Beta 1
Status: everything except 'resolved' and 'closed'
severity' category: Bug-Normal

Result were 26 bugs.

**Comment by SebastianBoell** [comment]
Did the third lot today imported all bugs from bugzilla using the filters:
Product: Compendium
Version: 2.0 Beta 1
Status: everything except 'resolved' and 'closed'
severity' category: Bug-Minor; Bug Trivial

Result were 15 bugs. This concludes importing all open bugs for Compendium 2.0 Beta from Bugzilla :) (in total 52 bugs).

Some stats on what is still missing in the exact order I intend to work through them:
- 7 misc. issues for 2.0 Alpha
- 4 bugs with no specific version set
- 29 Feature Requests for 2.0 Beta
- 20 Support Queries for 2.0 Beta
- 150 feature suggestions with no specific version set
- There are also 287 other open issues of various kinds referring to version 1.4 to 1.5.3 Alpha 5 which **I do not intend to look at or import**

UPDATE: see below I actuallay intend to review feature suggestions for verision 1.4 to 1.5.3 Alpha 5. See also issue #106

**Comment by maiklos** [comment]
ok, good job.
do you want to track some more activity with #33 issue or just close it now ?

**Comment by SebastianBoell** [comment]
Almost there. Right now the compendium website seems to be down. As soon as it is up again  I will get the open issues for alpha (7) and the four version independent other bugs. And finally have a look at the 20 support queries to see if they are referring to bugs and if they are still valid.

After that I will close this issue and open a new issue regarding reviewing the 179 feature suggestions (and the outcomes from the Compendium meeting in December). Depending on how they look I may start a review in the Wiki which will allow me to provide a more coherent picture of feature suggestions so that we get an overall idea rather than being inundated with tons of open tickets. Just thinking about it it may even be better to create an 'information base' in Compendium with all the feature suggestions. This will allow easy grouping re-arranging, planning, etc. ;)

**Comment by maiklos** [comment]
I vote for describing Compendium in wiki (sub-headline: to be). It is not necessary to fragment the description into ticket. When we have complex and coherent view of Compendium then for particular features tickets could be created and linked from description. 

btw.: Also there are some documents in the repository. We should asses their value/content and eventually merge them into wiki. I would prefer to have all documentation online (except for help)

**Comment by SebastianBoell** [comment]
Ok this issue is now done. 
- I have imported **[all 61 bugs](http://compendium.open.ac.uk/bugzilla/buglist.cgi?query_format=advanced&bug_severity=Bug-Blocker&bug_severity=Bug-Critical&bug_severity=Bug-Major&bug_severity=Bug-Normal&bug_severity=Bug-Minor&bug_severity=Bug-Trivial&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=VERIFIED&version=other&version=2.0%20Alpha%209&version=2.0%20Beta%201&product=Compendium)** that are were _not_ marked as _resolved_ or _closed_ in bugzilla regarding _Compendium 2.0 beta_ and _Compendium 2.0 alpha_, as well as all bugs related to _other_. I also added referrals to our issue system of CompendiumNG in bugzilla for every bug.
- I have reviewed **[all 41 support queries](http://compendium.open.ac.uk/bugzilla/buglist.cgi?query_format=advanced&bug_severity=Support%20Query&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=VERIFIED&version=other&version=2.0%20Alpha%209&version=2.0%20Beta%201&product=Compendium)** that are were _not_ marked as _resolved_ or _closed_ reported in bugzilla regarding _Compendium 2.0 beta_ and _Compendium 2.0 alpha_, as well as all support queries related to _other_. Where applicable they were reported as bugs, included into the FAQ of our wiki, or included into our list of feature suggestions. I also added referrals to CompendiumNG in bugzilla for every support query indicating how we handled it.
- Regarding conversion of document on the development of compendium into the wiki I have created issue #107 
- Regarding feature suggestions I have created issue #106 seeking to review and consolidate **approximately 430 feature suggestions** that we know of.
