### ISSUE TITLE
implement CI 

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#34]
project will benefit from CI approach. Currently there are not any useful tests however it would be useful to implement CI into the development process early.

**Comment by maiklos** [comment]
# Evaluation

currently I am evaluating some CI providers who are willing to provide CI for FOSS projects for free.
TravisCI, Cloudbees, CircleCI, teamcity

## CircleCI

I don't rememeber how I came to this but they are not  focused on FOSS projects.
(despite of being the staff was very helpful in my trial)

## TravisCI:

this one is really community driven (TravisCI software itself is FOSS: https://github.com/travis-ci)

currently set-up for CompendiumNG here: http://travis-ci.org/CompendiumNG/CompendiumNG

### pro
- easy to setup and pretty much works out of the box

### cons
- sunjdk6 is not available (due to Oracle EOL policy- which is ill approach from TravisCI ppl)

## Cloudbees

### pros & cons
- advanced vs complex

this one is based on Jenkins (note: jenkins doesn't equal to Hudson although they have common roots)
project is setup here: http://compendium-ng.ci.cloudbees.com (anonymous access)
This one is probably much more flexible than TravisCI (but also more complex)

There is Build-time-limit for FOSS project. I had to apply for free FOSS hosting and it bounds us to
(tweet about them, and put their log on the project site)

## teamcity (bettercode)

I have applied for FOSS hosting but dont' have any reaction from them yet.

**Comment by SebastianBoell** [comment]
I think a CI is a great thing to have. I like the ability by TravisCI to directly indicate of current build status on our Wiki. I guess it depends on how much work it is to maintain we can go with more the one for now and see how they are shaping up.

**Comment by maiklos** [comment]
cloudbees(jenkins) has the also the status though via plugin.I have installed the plugin and added the the status icon on wiki together with TravisCI status so codebees status is there too now.

btw. TravisCI status for master build is incorrect (it seems like a bug). master build failed due to setting but rebuild for master branch can be triggered only by a commit. When you click on a red(failed) icon for TravisCI it will lead you to succesful build (M1) - not to the failed one. Pretty confusing and ugly because we have "red" icon while it should be green :-)

...and of course we can have more than one CI. TravisCI is almost zero maintenance but also it has some limitations. So far it seems jenkins(cloudbees) might be the the right choice (in spite of higher maintenance effort).

I want to try bettercode (teamcity) prior to final decision.

**Comment by SebastianBoell** [comment]
It seems you did some work, as status has changed to green on both :) 

Keeping it simple is always good so maybe we want to go with only one CI once testing is done. But no rush!

**Comment by maiklos** [comment]
Hi Sebastian,
I think if I don't get any response from bettercode then we can safely stay
on cloudbees. I did some tuning/customization yesterday and now it shows
also some useful reports about code quality (not so nice number though).
Jenkins seems to be much more flexible and extensible than travis CI.

https://compendium-ng.ci.cloudbees.com/job/compendium-ng/

btw. the status became greenish due to the fact that I push a little change
to the master branch what triggered rebuild.

Michal

**Comment by maiklos** [comment]
let's stay with Cloudbees as the primary CI provider.
TravisCI is not sufficient.

CI cloudbees is now configured with some useful reports.
Closing this ticket as finished.

**Comment by SebastianBoell** [comment]
great! By the way what is happening with the couldbees repository for downloading current builds of compendium? It seems nothing is in there. I guess setup of these is not completed?

**Comment by maiklos** [comment]
I think we will discard this possibility. cloudbees will only publish
artifacts but it is not enough for installing/running compendium. I afraid
we have to extend it with installer first so cloudbees is able to publish
something useful for end user.
