### ISSUE TITLE
Some movie file formats cause Compendium to crash

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#36]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=857

Michelle Bachler 2010-04-30 20:53:23 BST

Some movie file formats cause Compendium to crash.

Andrew is re-writing parts of the fobs4 library. Has only done Windows version
at present. When all platform versions are available, this will be integrated
into Compendium and a new release will go out.

**Comment by SebastianBoell** [comment]
Not sure how heavily movie maps are used. I suggest to treat this as something to be stripped back from an initial release of CompendiumNG. Otherwise we should create a list of major video file types and test them with Compendium under Linux, Windows, Mac.

**Comment by maiklos** [comment]
it seems FOBS is discontinued [http://fobs.sourceforge.net/]. Dependency on this (and related features) was removed from CompendiumNG in 81d33621ace270a025ac7c6433631cf8743d3548
