### ISSUE TITLE
Error: (ViewPane.UI.CreateNode.actionPerformed)

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#38]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=891

Issue reported for Linux

NodeService is null in View.addMemberNBode-2c

Error kills right click context menu and keyboard shortcuts for node creation.

Can't really say I did anything new except rename the project. 

Fix: Restart Compendium

**Comment by SebastianBoell** [comment]
Not sure about this issue, what it means what it requires, or how it could be replicated. It is marked as major in bugzilla. Michal if you don't have an idea I suggest closing.

**Comment by maiklos** [comment]
a lot of code refactoring was done so exceptions and errors are properly logged. If there is debug log with occurrence of this error we can tend to it otherwise (from description) it is not reproducible and not fixable.

closing - can be reopened if new cases and better description is available.
