### ISSUE TITLE
Creating new projects with blank MySQL database doesn't work

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#39]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=927

Eugene Eric Kim 2010-10-05 02:51:07 BST

If you try connecting to a blank MySQL database, it fails. You need to manually
create the Project and Properties tables.

This seems to be a problem across all three platforms -- Mac, Windows, and
Linux.

[reply] [-] Comment 1 Michelle Bachler 2010-10-05 09:47:34 BST

Did you give the MySQL user sufficient rights to create/delete databases and
tables?

I just tried connecting my Windows Compendium 2.0 Beta1 to a MySQL installation
on my Cohere Linux server (which I have never done - so it is a new setup). I
created a MySQL user with all permissions. I created a new connection from
Compendium using that user and it created the compendium admin database and
projects table etc fine. I then create my first project on that server, and all
that went fine too.

I have not tried this from a Mac yet. I will do so later.

Michelle

[reply] [-] Comment 2 Eugene Eric Kim 2010-10-05 14:07:07 BST

Yes. I used GRANT ALL PRIVILEGES to give the Compendium user in MySQL all the
proper privileges.

**Comment by maiklos** [comment]
we need to reproduce and confirm this with current M1 version (with debug logging on). According to my testing I did few days ago it worked.

This might be related to #25

**Comment by maiklos** [comment]
not reproduced. Closing.
