### ISSUE TITLE
Can't delete nodes or maps, Aerial View is non-responsive and hourglass won't go away

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#40]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=946

Gillian Kerr 2010-11-09 02:19:59 GMT

I don't know whether these issues are related: Aerial View shows nodes that are
invisible in the Home Window. When I move a node or map in one view it doesn't
show the change in the other view. I can't delete any node or map in any view -
Aerial or Home or in the outline view, or in any other view. When I try to
delete a node or map, the hourglass comes up and stays until I close the
program.

[reply] [-] Comment 1 Michelle Bachler 2010-12-16 09:42:55 GMT

Hi!

I am sorry for the delay in looking at this issue.
I assume you are still experiencing this and it was not a one-off occurence.

Could you email me the compendium log files from this session
(m.s.bachler@open.ac.uk), they may help figure out what happened.
<compendium dir>/System/resources/Logs. They all have date and time stamps for
file names which should help.

If you do not use the aerial view at all during a given session, can you delete
nodes from maps or from the outline view? I guess what I am trying to establish
is if it was the using of the areial view that caused a subsequent issue with
deleting in other views, or not.

Thanks 

Michelle

**Comment by SebastianBoell** [comment]
I played around with the areal view and the home view respectively, but could not recreate the behaviour described here. As this issue is open for two years and no comments or advances seemed to have been made I suggest to close it as invalid / wontfix.

**Comment by maiklos** [comment]
I agree, unless we have (ideally) reproducible occurrence with current version of CompendiumNG I am closing this.
If new evidence is available we can reopen and track the bug.
