### ISSUE TITLE
Drag and dropped files get wrong path on Linux

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#43]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=995

Mike 2011-05-19 21:43:01 BST

I drag and drop a file with the name 
"A file with an €.txt" 
(no space at the end) from a file manager into a map and choose "as link to
original". 
If I dnd from Nautilus the reference node gets this path
"file:/home/example/A%2520file%2520with%2520an%2520%25E2%2582%25AC.txt%0D"
and this name
"A%20file%20with%20an%20%E2%82%AC.txt " .

From Konqueror:
"file:/home/net/A%20file%20with%20an%20€.txt" 
and
"A file with an €.txt"

Dnd from Thunar just does nothing.

A double click on the reference nodes just opens the properties window. There
is no error message as in issue 767. There are no log entries. The problem is
the same with a MySQL and Derby database. 

Ubuntu 10.10, Java-6-sun

[reply] [-] Comment 1 Mike 2011-05-19 22:26:09 BST

There are no log entries for the drag n drop. But there is one if I try to open
the reference node later:
: Exception: (ExecuteControl.launch) Cannot run program "/usr/bin/mozilla":
java.io.IOException: error=2, No such file or directory

I installed seamonkey-browser, which provides /usr/bin/mozilla on Ubuntu. After
that the reference node from Konqueror opens in Seamonkey, but the one from
Nautilus gets an "file not found" error in Seamonkey. 
But even if the file gets opened in Seamonkey it is handled in a different way
than a file with the usual path "/home/net/A file with an €.txt". This is the
path it gets if I use the "Browse" button within the properties window of the
ref node.

[reply] [-] Comment 2 Michelle Bachler 2011-05-20 10:03:44 BST

Unfortunately I don't have all the flaouvrs of Linux, or the time to really
test them. We only say that we have tested on Red Hat, beacuse that is what we
have here.

If you drag and drop from outside Compendium into Compendium, Compendium gets
passed the data. The data it is passed is determined by the operating system,
not Compendium unfortunately.

When you ask Compendium to open a link when on Linux, it first checks it see if
you have uselected that you se KFM Client in the Tools / User Options / Misc.
If you do, it branches off and calls the Operating system with exec
"/usr/bin/kfmclient" and the path you want to open. 

If you don't have use KFM Client selected, it checks the path to determine if
it is a URL or what the file type is. It then checks to see if you have already
picked before which application to launch that file type with, by checking a
property file in <compendium
dir>/System/resources/LaunchApplications.properties. Here we setup the
following default data:

www=/usr/bin/mozilla
http=/usr/bin/mozilla
https=/usr/bin/mozilla
html=/usr/bin/mozilla
htm=/usr/bin/mozilla
file=/usr/bin/mozilla

We then store subsequent choices for other file types in this file. So it will
ask you to select a programme for all file types, except the default ones, the
first time, and then use that programme next time. So, Compendium calls the
Operating system using the application specified in that file and passing the
path you want to open to that application.

You may need to edit this file if the paths are wrong for your installation, or
if things change.

I don't know if any of that information will help you determine if you can fix
the issue. Let me know if that helped and you managed to sort it out.

**Comment by SebastianBoell** [comment]
I could reproduce this on Debian Linux. If I drag and drop I get a dialogue asking me if I want to link or copy into linked files. If I select link I will get A%20file%20with%20an%20%E2%82%AC.txt If I select copy I get an error message '(no such file or directory)'.

**Comment by maiklos** [comment]
D'n'D operations of external resources is fundamental feature. It should be fixed soon. Tagging as as bug for M1

**Comment by maiklos** [comment]
note: behavior described in the original ticket is not true anymore. Using kcm-client  was removed in favor of platform independent way (Desktop) for opening external files. See #55

Also any links to a file must be stored in a platform independent way so they can be translated correctly in case you move your db from win to linux etc.
Probably best would be to pack all linked content into one zip/jar file where it can be referred in platform independent way or moved into a content repository.

**Comment by maiklos** [comment]
I am probably widening the scope of this ticket but while reading the dnd code in Compendium it will will need some refactoring before this bug can be fixed. Also I noticed that there are secondary "misbehaves" regarding DnD:

i.e. 
- select piece of text in Firefox and drag it on a map in Compendium. It will fail while trying to parse it as number. I would expect it to create a new node with the text in properties and some descriptive node label   (i.e. fragment from http://xxx.yyy...
- drag of locally store image (tried jpeg from desktop on Gentoo(LXDE), and JPEG from Thunar) also doesn't make anything - drop rejected (which is quite surprising for me)

while we are probably hitting platform specific stuff with DnD operation we should probably start with definition of how should CompendiumNG behave under various circumstances during DnD operations.

There is a potential with great improvement if it defined and implemented consistently and intuitively.

variable entering into it are:
- key modifiers (shift,control,Alt)
- dragged object type
- dragged object location (internet, local file, object from another map, etc.)
- source/application from which an object is dragged (on Linux we can hit many inconsistencies with this)

wiki page is here: [Drag-and-Drop-operations](https://github.com/CompendiumNG/CompendiumNG/wiki/Drag-and-Drop-operations)

**Comment by SebastianBoell** [comment]
Added the link to your post above. I also added some content to the wiki entry already. By the way DnD works under Debian (Gnome) with Nautilus. It opens a short dialogue asking if I want to link, copy into the linked files folder or 'cancel'.

**Comment by maiklos** [comment]
there was some strange fix for "something" which on Linux cut the last character. This is fixed in c413c45fa035b6e93bc766fde9a746763efbb818. This was causing problem on Linux when you dnd a file and choose "copy" it will  try to copy  instead of i.e. file: filename.txt file filename.tx. 

Also there is following problem: when  DnD/copy  is selected then the files is read into the memory and then written to the storage/disk. This might be problem for bigger files and eventually can cause memory issues or file corruption.
Another more efficient way should be found for copying files into the Linked Files (fixed in: cd98b1e)
- http://docs.oracle.com/javase/tutorial/essential/io/copy.html
- http://stackoverflow.com/questions/106770/standard-concise-way-to-copy-a-file-in-java

**Comment by maiklos** [comment]
fix provided for original problem. 
some file managers on linux when filename (or path) contains spaces encode them as URL (i.e <SPACE> -> %20).
Fix decodes the file name first so now are linked files in not encoded form. Tested on Nautilus, Dolphin, Konqueror.

both original problems are fixed now. The rest from this thread should be considered as feature request via FSP.
