### ISSUE TITLE
autoupdate check

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#47]
implement auto-update feature

eclipse based?  P2 ?

**Comment by SebastianBoell** [comment]
Currently there is already some functionality availiable that may help with this. As Compendium has the function 'check for updates' I guess this could be executed as part of the start-up of compendium. However, I remember a bug that Compendium is connecting to a central server on every startup. Once the server was down for a few days this lead to huge delays in the startup time of Compendium. That is if you waited 10 minutes or so on the startup screen Compendium was eventually starting. If we implement a check during startup we have to make sure that delays like the one described are to be avoided.

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/automatic-update/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
