### ISSUE TITLE
Tag indicator not appearing after insert into view from search

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#53]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=860

Michelle Bachler 2010-04-30 20:59:17 BST

Reported by Al Selvin.

The examples given where to do with nodes that had labels which contained one
or more words which where identical to tag names being search on.

**Comment by maiklos** [comment]
I am not sure if I understand. Steps to reproduce this will be needed

**Comment by SebastianBoell** [comment]
I think it is related to #52

**Comment by SebastianBoell** [comment]
I did some tinkering with tags and search. I could not reproduce this but in M1. When ever I enter a node from search that is tagged is appears with a correct tag indicator. Will close this issue.
