### ISSUE TITLE
Movies, pdf, website etc don't launch on Linux.

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#55]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=868

Michelle Bachler 2010-05-05 10:18:28 BST

First reported by Steve Brettell

Launching external apps, like for viewing the website link or the video, is
tricky on Linux. Different setups have different software in different
locations. Compendium is supposed to ask the user the first time it launches a
new file type or url and then when the user selects the application to use to
open it, it records this in a file so the next time Compendium can just launch
without asking. The file is:

<compendium dir>/System/resources/LaunchApplications.properties

I tried to make a guess at what I thought most people would have installed and
I seeded this file with various file types and a path to FireFox. Silly really.
I should have just left it blank. 

Solution:

If you go to the above LaunchApplications.properties file and just delete
everything in it so it is totally empty. Then restart Compendium. Now when you
click anything that needs to open an external application like a browser, you
should get a file dialog asking you to locate the application to use then it
should launch the url or movie etc.. The next time for the same file type, it
should just work. I will make sure I empty the file for the Beta 2 release.
Sorry.

**Comment by SebastianBoell** [comment]
I agree this is annoying. I guess our plan to centralize all settings and making them accessible through a menu interface would help in solving some parts of this problem. Possibly we can use some MIME type information available under Gnome/KDE to populate this list automatically. Not sure what to do on cloud based usage of Compendium which potentially can run on different OS. Maybe a MIME type list can be populated at start up with settings only being retained for those application associatons that were modified manually by a user.

**Comment by maiklos** [comment]
IMO this setting shouldn't be in compendium  at all. Compendium should respect system setting and use what is appropriate on particular platform. on linux xdg-open is often used. 

One thing I have hit today while fixing some code is that it is not quite clear how external resources should be opened even on windows. It is often not clear if some resource should be open for editing or for viewing. This might result in using completely different application.

**Comment by SebastianBoell** [comment]
Absolutely agree! 

If it is possible for Compendium to avoid dealing with this it should be removed!

**Comment by maiklos** [comment]
note:
recommended way to open a file in platform independent way from java:

http://docs.oracle.com/javase/6/docs/api/java/awt/Desktop.html

need to verify it.

**Comment by maiklos** [comment]
M1 is updated now in 77219be. Now opening external file or URL is not platform specific.
I made brief testing and it seems working.

please retest under various conditions.

**Comment by SebastianBoell** [comment]
This works so much better than before! I did some testing with:
- JPG
- PNG
- DOC
- AVI
- HTM / HTML
- PDF

Except PDF everything works fine. Actually PDF also opens acrobat but acrobat does not open the pdf. Curiously I changed the system default to document viewer, but Compendium still uses Acrobat, even after a system reboot and a reinstall of Compendium. However, the problem could be the settings on my machine as I can remember that it took me some time to set up Acrobat under Debian. Could you do a test with PDF on your machine?

Just one thing. I noticed that when ever I open a node that opens an external file Compendium first opens the node content window and leaves it open in the background this is a bit annoying. I think it would be better if it simply opens the external application.

**Comment by maiklos** [comment]
fix: when linked URL is being opened then don't open node contents dialog at all.
content dialog should be still displayed when open via context menu

**Comment by mike223** [comment]
Reference nodes with http-links are ok, but https ones only open the nodes Contents window in 2.1.1. 
Files seem to work as long as they are not entered as  file:/test.txt  but only  /test.txt

(CompendiumNG 2.1.1, java-6-sun, mysql-server-5.1, imported database from 2.0 Beta 1, Ubuntu 10.10)

**Comment by maiklos** [comment]
according to my testing on (on ubuntu linux) and reading the code:

a) when you drag/drop a local file and select to make only a link then reference field is in form: file:/file.txt
b) when you drag/drop a local file and select to copy it then the reference field is in form: /absolute_path_to_the_file/file.txt

on opening of the file when...
1) ...not running on windows then path to the file is left as is and opened
2) ...running on windows then "file:/ is stripped

I have made modification so..:
A) when opening anything starting with "file:" then "file:" is removed
B) all "/" and "\" are replaced with native path separators 
C) double separators are replaced with one separator
D) path is decoded via URL decoder in case it has some URL encoded character (like %20 for space etc.)

I believe this is robust enough so opening files should work better now even for incorrectly saved files paths in the reference field.
