### ISSUE TITLE
bad file permissions, as packaged

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#63]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=920

James 2010-08-17 03:57:06 BST

compendium-2.0-beta1.tar.gz for linux has almost all file permissions set to
700, no matter what the file.  So, for instance then, all image files - .gif
and .png - are executable - that's crazy.  And then also, all directories are
only readable by a single user - also crazy.  The exceptions to the 700
permissions are the two dot files, ._.DS_Store and .DS_Store.

Please clean up the permissions, so that only executable files are executable,
and so directory and file permissions are appropriate for shared use.

Thanks

James

[reply] [-] Comment 1 James 2010-08-17 04:36:53 BST

Ok, I suggest the following, to fix permissions and ownerships:

Suppose Compendium is installed to /opt/, then, using sudo in Ubuntu,

cd /opt/Compendium

sudo chown -R root:root *
sudo chown root:root ._.DS_Store .DS_Store

sudo find -type d -exec chmod 755 {} \;
sudo find -type f -exec chmod 644 {} \;

sudo chmod 755 Compendium.sh

sudo mkdir -m777 System/resources/Databases

James

[reply] [-] Comment 2 James 2010-08-17 04:51:32 BST

Oh - and of course, Compendium should be creating this Databases directory in
the user's home directory, under, say, ~/.compendium/ or maybe
~/.cache/compendium/.  That shouldn't be difficult.

James

[reply] [-] Comment 3 James 2010-08-17 04:58:36 BST

...unless this Databases directory must be shared, in order to support
collaborative mind-mapping.  I'm new to Compendium, and, so far, know nothing
about how the collaborative bits function.

James

[reply] [-] Comment 4 James 2010-08-17 06:15:10 BST

It seems that there also needs to be this:

sudo mkdir -m777 System/resources/Logs

Any others?

James

[reply] [-] Comment 5 Michelle Bachler 2010-08-23 10:26:58 BST

OK. I basically copy the Compendium folder of files from a Windows machine to a
Mac, then create a gzip file there using a terminall window. I have never
touched the file permissions in all the years I have been doing things this
way. It has never been an issue. 

I am wondering why no one has ever mentioned this before, or why it is an issue
now.

I will need to investigate this before the next release.

Michelle

**Comment by SebastianBoell** [comment]
I can confirm that a fresh install of Compendium from M1 sets most files to executable. Clearly this should not be the case. As these permissions are also existend in M1 I wonder if changing permissions for M1 and doing a push back to GitHub would solve this?

**Comment by maiklos** [comment]
it seems permission are set correctly in the repository.
when i clone the project the only executable are shell scripts. Couldn't that be setting of git ? ~/.gitconfig ?
umask ? or something else ?

**Comment by SebastianBoell** [comment]
I double checked and it also looks fine here. I guess this issue can be closed.
