### ISSUE TITLE
Cursor stays 'thinking' in the Outline View section

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#76]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=880

tom 2010-05-24 11:56:49 BST

Disconcerting for cursor to stay at egg-timer.

[reply] [-] Comment 1 Michelle Bachler 2010-05-24 12:01:26 BST

This may indicate an issue.

What exactly did you do in the Outline View?
Which Outline view option where you viewing (node and maps, or just maps)?
Did you perform an action in the Outline view when the hour glass started and
didn't stop, or did you just open the view?

Could you email me the Compendium log file from that session as it may have
some useful info(<compendium dir>/System/resources/Logs - they have date and
time stamps to help you locate the right one). Email to m.s.bachler@open.ac.uk

Thanks

Michelle

[reply] [-] Comment 2 Fiona 2010-06-02 03:51:35 BST

I am a new user.  However I have the same problem.  It seems to be only when I
click in the Home Window of the outline view.  If I click on Fiona's Home
Window the cursor stays in "thinking Mode".  If I click on a subfolder which is
a map node that I have creatd,  the cursor goes into thinking mode.
I appear to be able to get the Cursor out of thinking mode and back to working
properly by clicking in the Fionas Home Screen on any  Node that has been
created by Compendium - ie Inbox, Quick Start or "Thanks to the Compendiums
funders".  Is there an answer yet?

Regards Fiona

**Comment by SebastianBoell** [comment]
I can confirm this bug for the lastes branch from M1. When selecting some items in the outliine view the mouse courser stays in 'loading' mode. However, Compendium is still very responsive and opens entries in the outline view without a problem. Possibly the procedure is not correctly terminated that is why the 'loading' continues even though the item is done.

**Comment by maiklos** [comment]
this problem seems to be also fixed with #82
