### ISSUE TITLE
Entry for 'Welcome' screen in help menu is superfluous

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#79]
The first entry in the 'help' menu is 'welcome' which brings up the welcome screen. This menu item should be removed.
- When a project is open and the item is selected the welcome screen is placed over the current project with no option of removing the welcome screen. 
- The only time this entry makes sense is when no project is currently loaded. However, I suggest then it may be even better to bring up the 'welcome' screen automatically every time no project is loaded. Will create an according issue as well.

**Comment by maiklos** [comment]
fixed in: 64702
