### ISSUE TITLE
make CompendiumNG scriptable

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#8]
basic use cases:
user can make run a script to modify his/her model/map
user can generate the script via actions he/she is doing via UI and modify the script

Provide scripting framework based on a 1 or more popular languages so users can create their own scripts to manipulate their model. Languages that should be taken into consideration (candidates: jRuby, jython, javascript, java(beanshell), groovy, Fantom). Scritping language must support fundamental programming language concepts like: conditions, arrays, objects, variables, work with files, etc. (http://docs.oracle.com/javase/6/docs/technotes/guides/scripting/programmer_guide/index.html)

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/make-compendiumng-scriptable/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.

**Comment by mike223** [comment]
With the MySQL backend and Bash powerful (maybe even too powerful) scripting can be implemented without changing Compendium(NG):
https://github.com/CompendiumNG/CompendiumNG/wiki/Enhancing-Compendium(NG)-with-scripts:-The-result
It works pretty good for scripts run before Compendium. But there are difficulties to show the results from scripts run during a Compendium session: A refresh needs to be started by the user (or using a mouse recorder).
