### ISSUE TITLE
Slow performance at startup

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#87]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=948Pawel 2010-11-15 16:39:09 GMT

on my notebook 4gb ram, T7250 processor starting time is 1 minute 50 seconds

[reply] [-] Comment 1 Michelle Bachler 2010-11-16 10:15:55 GMT

ODD. I just tested my beta 1 and it took 15 seconds. I am on quite and old
windows machine. 

Do you have many projects? 
Do you have Compendium automatically open one for you on startup?
If so, do have a very large number of maps on your home page / in that project?

I am trying to think of things on startup that add time, but it should not be
much.

Michelle

[reply] [-] Comment 2 Pawel 2010-11-16 12:59:28 GMT

Hello Michelle,

Please kindly find my answers to your questions below:

> Do you have many projects? 

2

> Do you have Compendium automatically open one for you on startup?

no

> If so, do have a very large number of maps on your home page / in that project?

no, in default project which opens automatically I have 5 maps

[reply] [-] Comment 3 Michelle Bachler 2010-11-16 14:49:01 GMT

OK. It is hard for me to say why Java/Compendium is running so slowly on your
machine. I cannot reproduce it, and I have not, so far, had any other user's
reporting this behaviour.

It might be worth putting this on the Compendium Yahoo group and asking if
anyone else has this issue. I am not sure how best to help you.

Michelle

**Comment by SebastianBoell** [comment]
Again, there is too little information on what the exact problem is and no progress for two years. I will close this issue.

**Comment by maiklos** [comment]
test:
Linux  3.4.4ms SMP PREEMPT Sun Jul 8 17:35:08 CEST 2012 i686 Intel(R) Core(TM)2 Duo CPU T8100 @ 2.10GHz GenuineIntel GNU/Linux, 4GB RAM, notebook, Funtoo(gentoo) linux

Run from eclipse IDE it takes around 5 seconds to start (show project list)  [sunjdk6 and icedtea7]
from selecting a trivial project it takes 1-2 secs to fully open it.

issue might be with more complex projects though.
