### ISSUE TITLE
Closing a movie map with a running movie still playing can crash Compendium

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#97]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=841

Michelle Bachler 2010-02-12 13:55:47 GMT

It does not happen all the time. It is random and seldom.
It is probably a timing thing with the movie code closing various bits.
Not sure really.

**Comment by SebastianBoell** [comment]
I already fail when trying to add a movie to movie maps under Linux in M1. I am not sure if movie maps are to be retained as part of M1? (see  issue #36) indicating that FOBS, the media mapper previously used by Compendium was discontinued. An alternative may be MLT? But then working the nuts and bolts of a multimedia toolkit is maybe something that will distract us from some more urgent changes.

**Comment by maiklos** [comment]
I confirm, this and meeting feature was removed due to dependencies on fobs. Multimedia feature and movie maps will need to be reimplemented with different library. 

I would suggest to close this and instead define feature request for multimedia feature.

**Comment by SebastianBoell** [comment]
I will work on a feature request description of this and then close this issue soon (as part of #106). I also added a note to the changes notes regarding M1 on the wiki indicating that multimedia support was discontinued as part of M1 but will be brought back later. Not sure you agree on this one, but my judgement is that we won't be able to fix is within the comming weeks, hence as part of M1.

I guess as a result of this we would have to dissable 'movie maps' in M1, that is hiding it from menus and toolbars, as well as removing  references to it in the help file.

**Comment by maiklos** [comment]
I fully agree with your comment. I will remove UI elements that are related to removed feature. Reimplementation - not sure - probably "future releases" ( may re-evaluate it later)

**Comment by SebastianBoell** [comment]
This issue is now closed at the problem no longer applies to CompendiumNG from M1 forward (see #116 and #117). Support for multimedia was removed as the relevant package (fobs) is no longer in active development. However, we intend to re-implement this functionality again in the future. This means that this probpem is effectively superseeded by issue #118.
